import { randomUUID } from "node:crypto";
import { existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,rmSync,writeFileSync } from "node:fs";
import { join } from "node:path";import { tmpdir } from "node:os";import Database from "better-sqlite3";
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { dispatchJsonBusinessRequest } from "@backend-runtime/json-business/index";
import { publicJsonBusinessResult } from "@shared/json-business-contract.mjs";
import * as memory from "@backend-runtime/lib/memory-search";import * as unread from "@backend-runtime/lib/unread-state";import * as sampling from "@backend-runtime/lib/sysmon-usage";import { createNodeSysFs } from "@backend-runtime/lib/sysmon-linux";
import { emptyUsage } from "@shared/sysmon";
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-information-owner-"));for(const [key,value]of Object.entries({LEAFCODE_PI_PROCESS_ROLE:"backend",LEAFCODE_PI_BACKEND_RUNTIME:"attach",LEAFCODE_PI_DATA_DIR:join(root,"data"),PI_CODING_AGENT_DIR:join(root,"agent"),LEAFCODE_SYSMON_NVIDIA_SMI:"__fixture_missing_nvidia__",LEAFCODE_SYSMON_POWERSHELL:"__fixture_missing_powershell__",LEAFCODE_SYSMON_THERMAL:"0"}))vi.stubEnv(key,value);sampling.resetSystemUsageCacheForTests();});
afterEach(()=>{memory.resetMemorySearchDatabaseCacheForTests();vi.restoreAllMocks();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
async function request(route:string,method:string,body?:unknown,id:string=randomUUID(),authorized=true,origin?:string){const result=await dispatchJsonBusinessRequest({route,method,url:"http://localhost/api/"+route,headers:{host:"localhost",...(origin?{origin}:{})},authorized,operationId:id,...(body===undefined?{}:{body:new TextEncoder().encode(typeof body==="string"?body:JSON.stringify(body))})});const projected=publicJsonBusinessResult(route,result,method);expect(projected).not.toBeNull();return projected! as typeof result & {body:Record<string,any>};}
function seed(){const dir=join(root,"agent","leafcode-memory");mkdirSync(dir,{recursive:true});const file=join(dir,"sessions.db"),db=new Database(file);db.exec("CREATE TABLE memories(id INTEGER PRIMARY KEY,project TEXT,target TEXT,category TEXT,content TEXT,created TEXT,last_referenced TEXT);");db.prepare("INSERT INTO memories VALUES(1,NULL,'memory','convention',?,'fixture','fixture')").run("Fixture authored 日本語 token narrative");db.close();return file;}
it("real read-only SQLite search preserves authored content, ignores caller path/scope and never writes ledger or references",async()=>{const file=seed(),bytes=readFileSync(file);const result=await request("memory-search","POST",{query:"日本語",path:join(root,"forged.db"),project:"forged",target:"user"});expect(result.status).toBe(200);expect(result.body.results[0].content).toContain("authored 日本語");expect(readFileSync(file)).toEqual(bytes);expect(existsSync(join(root,"data"))).toBe(false);expect(existsSync(join(root,"forged.db"))).toBe(false);for(const body of [{query:""},{query:"x".repeat(201)},null,[],"{bad"] )expect((await request("memory-search","POST",body)).status).toBe(400);});
it("unread persists positive newest markers for bot/room/task and prototype-like IDs, serial replay and unrelated settings survive",async()=>{mkdirSync(join(root,"data"));writeFileSync(join(root,"data","web-settings.json"),JSON.stringify({version:1,unrelated:"preserved"}));for(const [kind,id]of [["bot","constructor"],["room","__proto__"],["task","toString"]]){expect((await request("unread","PUT",{kind,id,readAt:200,path:"forged"})).body.readAt).toBe(200);expect((await request("unread","PUT",{kind,id,readAt:100})).body.readAt).toBe(200);}const result=await request("unread","GET");expect(result.body.markers).toHaveLength(3);expect(result.body.markers.every((m:any)=>m.readAt===200)).toBe(true);expect(JSON.parse(readFileSync(join(root,"data","web-settings.json"),"utf8")).unrelated).toBe("preserved");const id=randomUUID();expect((await request("unread","PUT",{kind:"task",id:"one",readAt:1},id)).status).toBe(200);expect((await request("unread","PUT",{kind:"task",id:"one",readAt:999},id)).status).toBe(409);expect(unread.getUnreadReadMarkers().find(m=>m.id==="one")?.readAt).toBe(1);const ledger=readFileSync(join(root,"data","unread-command.json"),"utf8");expect(ledger).not.toMatch(/constructor|__proto__|readAt|unrelated|one|forged/);});
it("auth/Origin/body bounds and development Next refuse before DB, cache, FS or commands",async()=>{const search=vi.spyOn(memory,"searchLeafCodeMemory"),collect=vi.spyOn(sampling,"collectSystemUsageCached"),mark=vi.spyOn(unread,"markUnreadRead");expect((await request("memory-search","POST",{query:"fixture"},randomUUID(),false)).status).toBe(401);expect((await request("sysmon/usage","GET",undefined,randomUUID(),false)).status).toBe(401);expect((await request("unread","PUT",{},randomUUID(),true,"https://evil.invalid")).status).toBe(403);expect((await request("memory-search","POST","x".repeat(4097))).status).toBe(413);expect((await request("unread","PUT","x".repeat(4097))).status).toBe(413);expect(search).not.toHaveBeenCalled();expect(collect).not.toHaveBeenCalled();expect(mark).not.toHaveBeenCalled();const fs=createNodeSysFs();vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");vi.stubEnv("NODE_ENV","development");for(const fn of [()=>memory.searchLeafCodeMemory("fixture"),()=>sampling.collectSystemUsage(),()=>sampling.collectSystemUsageCached(),()=>unread.getUnreadReadMarkers(),()=>unread.markUnreadRead("task","id",1),()=>createNodeSysFs(),()=>fs.readFile("forged")])await expect(Promise.resolve().then(():unknown=>fn())).rejects.toThrow(/owned by Backend/);expect(readdirSync(root)).toEqual([]);});
it("probe failure is a sanitized 200 unavailable, malformed cached success fails 503 before nonfinite serialization",async()=>{vi.spyOn(sampling,"collectSystemUsageCached").mockRejectedValueOnce(new Error("PRIVATE command path"));const failure=await request("sysmon/usage","GET");expect(failure.status).toBe(200);expect(failure.body.available).toBe(false);expect(JSON.stringify(failure)).not.toContain("PRIVATE");vi.spyOn(sampling,"collectSystemUsageCached").mockResolvedValueOnce({...emptyUsage(),available:true,cpu:{usedPercent:Infinity,cores:1,model:"fixture",tempC:null},memory:{usedPercent:1,usedBytes:1,totalBytes:100}});expect((await request("sysmon/usage","GET")).status).toBe(503);});
it("invalid markers are complete refusals; post-save typed errors remain unknown and saved bytes are not rolled back",async()=>{for(const body of [{kind:"bad",id:"id",readAt:1},{kind:"task",id:"",readAt:1},{kind:"task",id:"id",readAt:0},null]){const result=await request("unread","PUT",body);expect(result.status).toBe(400);expect(result.body.operation.execution).toBe("complete");}const original=unread.markUnreadRead;vi.spyOn(unread,"markUnreadRead").mockImplementationOnce((...args)=>{original(...args);throw Object.assign(new Error("PRIVATE"),{status:400});});const id=randomUUID(),result=await request("unread","PUT",{kind:"task",id:"saved",readAt:88},id);expect(result.status).toBe(503);expect(result.body.operation.execution).toBe("unknown");expect(unread.getUnreadReadMarkers().find(row=>row.id==="saved")?.readAt).toBe(88);expect((await request("unread","PUT",{kind:"task",id:"saved",readAt:999},id)).status).toBe(409);expect(JSON.stringify(result)).not.toContain("PRIVATE");});
it("corrupt settings/ledger refuse persistence and preserve original bytes; GET keeps legacy tolerant fallback",async()=>{mkdirSync(join(root,"data"));const file=join(root,"data","web-settings.json");writeFileSync(file,'{"PRIVATE":BROKEN');const result=await request("unread","PUT",{kind:"task",id:"id",readAt:1});expect(result.status).toBe(503);expect(result.body.operation.execution).toBe("unknown");expect(readFileSync(file,"utf8")).toBe('{"PRIVATE":BROKEN');expect((await request("unread","GET")).body.markers).toEqual([]);writeFileSync(join(root,"data","unread-command.json"),"broken");const refused=await request("unread","PUT",{kind:"task",id:"id",readAt:1});expect(refused.status).toBe(503);expect(refused.body.operation.execution).toBe("not-started");});
it("cached system sampling remains Backend-only even after warming; no command values enter DTO",async()=>{const result=await request("sysmon/usage","GET");expect(result.status).toBe(200);expect(result.body.available).toBe(true);const second=await request("sysmon/usage","GET");expect(second.body.generatedAt).toBe(result.body.generatedAt);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");await expect(sampling.collectSystemUsageCached()).rejects.toThrow(/owned by Backend/);});
