import { randomUUID } from "node:crypto";
import { mkdtempSync,readdirSync,readFileSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { beforeEach,afterEach,describe,expect,it,vi } from "vitest";
import * as bots from "@/lib/bots";
import * as store from "@/lib/store";
import * as harness from "@/lib/pi/harness";
import * as relay from "@/lib/pi/bot-code-relay";
import * as goal from "@/lib/pi/goal-loop-state";
import * as lease from "@/lib/task-runtime-lease";
import * as entrances from "@backend-runtime/lib/bot-code";
import { dispatchJsonBusinessRequest } from "@backend-runtime/json-business/index";
import { publicJsonBusinessResult } from "@shared/json-business-contract.mjs";
const botId="11111111-0123-4321-abcd-eeeeeeeeeeee",requestId="a".repeat(64);
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-bot-code-"));vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_BACKEND_RUNTIME","attach");vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",join(root,"agent"));vi.spyOn(lease,"reconcileOrphanedWorkingTasks").mockReturnValue([] as never);});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
const summary=()=>({id:"code",kind:"code",botId,status:"idle",directory:root,sessionId:null,token:"PRIVATE"} as never);
const loop=()=>({id:"loop",sessionId:"session",status:"queued",goal:"authored 日本語",maxTurns:3,turnCount:1,progress:[{time:"1",status:"progress",summary:"authored",token:"PRIVATE"}],token:"PRIVATE"} as never);
function exists(patch={}){return vi.spyOn(bots,"getBot").mockReturnValue({id:botId,enabled:true,permissionMode:"ask",codeSessionTaskId:"code",...patch} as never);}
async function request(action="code-session",method="GET",body?:unknown,id=randomUUID(),authorized=true,origin?:string,signal?:AbortSignal,selector=botId,etag?:string){const path=`bots/${selector}/${action}`,result=await dispatchJsonBusinessRequest({route:path,method,url:`http://localhost/api/${path}`,headers:{host:"localhost",...(origin?{origin}:{}),...(etag?{"if-none-match":etag}:{})},authorized,operationId:method==="GET"?undefined:id,signal,body:body===undefined?undefined:new TextEncoder().encode(typeof body==="string"?body:JSON.stringify(body))});const dto=publicJsonBusinessResult(path,result,method);expect(dto).not.toBeNull();return {...dto!,body:dto!.body!};}
describe("Bot Code Backend owner",()=>{
 it("reads projected panel/loops and request results/progress with ETag, settled peeks skipped and no ledger",async()=>{
  exists();const panel=vi.spyOn(harness,"getBotCodeSessionPanelState").mockResolvedValue({tasks:[summary()],loops:{code:loop(),foreign:{token:"PRIVATE"}}} as never),requests=vi.spyOn(relay,"listBotCodeRequests").mockReturnValue([{id:requestId,codeTaskId:"code",state:"running",prompt:"authored",token:"PRIVATE"},{id:"b".repeat(64),codeTaskId:"cold",state:"delivered",prompt:"legacy",result:JSON.stringify({outcome:"done",output:"authored tool text",goalLoop:{status:"completed",evidence:"authored",token:"PRIVATE"},token:"PRIVATE"})}] as never),peek=vi.spyOn(harness,"peekCodeRequestProgress").mockResolvedValue({todoProgress:{completed:1,total:2,token:"PRIVATE"},activity:"read",goalLoopSummary:{status:"queued",maxTurns:3,turnCount:1,token:"PRIVATE"}} as never);
  for(const action of ["code-session","code-requests"]){const first=await request(action);expect(first.status).toBe(200);expect(JSON.stringify(first.body)).not.toContain("PRIVATE");expect((await request(action,"GET",undefined,undefined,true,undefined,undefined,undefined,first.headers.etag)).status).toBe(304);}expect(panel).toHaveBeenCalledWith(botId);expect(requests).toHaveBeenCalledWith(botId);expect(peek).toHaveBeenCalledTimes(2);expect(peek).toHaveBeenCalledWith("code");expect(readdirSync(root)).toEqual([]);
 });
 it("start selects only authorized settings and rejects archived/missing projects, malformed Goal, disabled/deny Bots",async()=>{
  const bot=exists(),project=vi.spyOn(store,"getProject").mockReturnValue({id:"p",archived:false} as never),create=vi.spyOn(harness,"createBotCodeTask").mockResolvedValue(summary());
  const id=randomUUID(),result=await request("code-session","POST",{projectId:" p ",prompt:"authored",model:" owner::model ",thinkingLevel:"high",permissionMode:"ask",goalLoop:{acceptance:[" owner "],maxTurns:999,cooldownSeconds:999999,forceFullRun:true},botId:"other",taskId:"foreign",codeRequestId:"FORGED",beforePrompt:"FORGED",images:["FORGED"]},id);
  expect(result.status).toBe(200);expect(create).toHaveBeenCalledExactlyOnceWith(botId,{projectId:"p",prompt:"authored",model:"owner::model",thinkingLevel:"high",permissionMode:"ask",goalLoop:{acceptance:["owner"],maxTurns:100,cooldownSeconds:86400,forceFullRun:true}});expect(JSON.stringify(result.body)).not.toContain("PRIVATE");expect((await request("code-session","POST",{},id)).status).toBe(409);expect(create).toHaveBeenCalledOnce();
  project.mockReturnValueOnce({archived:true} as never);expect((await request("code-session","POST",{projectId:"p",prompt:"x"})).status).toBe(409);project.mockReturnValueOnce(undefined);expect((await request("code-session","POST",{projectId:"p",prompt:"x"})).status).toBe(404);
  for(const body of [{projectId:null,prompt:"x",goalLoop:{acceptance:2}},{projectId:null,prompt:"x",thinkingLevel:"invalid"},{projectId:null,prompt:"x",permissionMode:"privilege"}])expect((await request("code-session","POST",body)).status).toBe(400);
  for(const config of [{enabled:false},{permissionMode:"deny"}]){bot.mockReturnValueOnce({id:botId,...config} as never);expect((await request("code-session","POST",{projectId:null,prompt:"x"})).status).toBe(403);}expect(create).toHaveBeenCalledOnce();const ledger=readFileSync(join(root,"bot-code-command.json"),"utf8");for(const value of [botId,"authored","owner::model","FORGED"])expect(ledger).not.toContain(value);
 });
 it("targeted request Stop belongs only to the owner, preserves produced work and runs completion even after typed abort failure",async()=>{
  exists();const stop=vi.spyOn(relay,"stopBotCodeRequest").mockResolvedValue({state:"running",codeTaskId:"code"}),abort=vi.spyOn(harness,"abortTaskIncludingColdGoalLoop").mockResolvedValue(summary()),complete=vi.spyOn(harness,"completeBotCodeRequest").mockResolvedValue(undefined);
  const first=await request("code-requests","POST",{action:"abort",requestId,botId:"foreign",taskId:"foreign"});expect(first.status).toBe(200);expect(stop).toHaveBeenCalledExactlyOnceWith(botId,requestId);expect(abort).toHaveBeenCalledExactlyOnceWith("code");expect(complete).toHaveBeenCalledExactlyOnceWith(requestId);
  abort.mockRejectedValueOnce(Object.assign(new Error("PRIVATE after-stop"),{status:409}));const id=randomUUID(),partial=await request("code-requests","POST",{action:"abort",requestId},id);expect(partial.status).toBe(503);expect(partial.body).toMatchObject({operation:{execution:"unknown"}});expect(JSON.stringify(partial.body)).not.toContain("PRIVATE");expect(complete).toHaveBeenCalledTimes(2);expect((await request("code-requests","POST",{action:"abort",requestId},id)).status).toBe(409);expect(stop).toHaveBeenCalledTimes(2);
  stop.mockResolvedValueOnce(undefined);expect((await request("code-requests","POST",{action:"abort",requestId})).status).toBe(404);for(const forged of ["../x","BAD",null])expect((await request("code-requests","POST",{action:"abort",requestId:forged})).status).toBe(400);expect(stop).toHaveBeenCalledTimes(3);
 });
 it("Stop stays concurrent with blocked Code launch and an admitted disconnect cannot replay launch",async()=>{
  exists();vi.spyOn(store,"getTask").mockReturnValue(summary());vi.spyOn(relay,"isRoomDelegatedCodeTask").mockReturnValue(false);let finish!:(value:never)=>void;const create=vi.spyOn(harness,"createBotCodeTask").mockImplementation(()=>new Promise(resolve=>{finish=resolve;})),stop=vi.spyOn(harness,"stopBotCodeTask").mockResolvedValue(summary()),controller=new AbortController(),id=randomUUID();
  const held=request("code-session","POST",{projectId:null,prompt:"held"},id,true,undefined,controller.signal);await vi.waitFor(()=>expect(create).toHaveBeenCalledOnce());expect((await request("code-session","PATCH",{action:"abort",taskId:"code"})).status).toBe(200);expect(stop).toHaveBeenCalledExactlyOnceWith(botId,"code");controller.abort();finish(summary());expect((await held).status).toBe(200);expect((await request("code-session","POST",{},id)).status).toBe(409);
 });
 it("supervised Code may be controlled; Room and other Bot tasks cannot be prompted, aborted or unlinked",async()=>{
  exists();const get=vi.spyOn(store,"getTask"),room=vi.spyOn(relay,"isRoomDelegatedCodeTask").mockReturnValue(false),prompt=vi.spyOn(harness,"continueBotCodeTask").mockResolvedValue(summary()),stop=vi.spyOn(harness,"stopBotCodeTask").mockResolvedValue(summary());
  get.mockReturnValue({...summary() as object,botId:null,supervisorBotId:botId} as never);expect((await request("code-session","PATCH",{action:"prompt",taskId:"code",prompt:" authored "})).status).toBe(200);expect(prompt).toHaveBeenCalledExactlyOnceWith(botId,"code","authored");
  for(const target of [{id:"other",kind:"code",botId:"other",status:"idle"},{id:"worker",kind:"bot",botId,status:"idle"},{id:"room-code",kind:"code",botId,status:"idle"}]){get.mockReturnValue(target as never);room.mockReturnValue(target.id==="room-code");for(const action of ["prompt","abort","unlink"])expect((await request("code-session","PATCH",{action,taskId:target.id,prompt:"x"})).status).toBe(404);}expect(prompt).toHaveBeenCalledOnce();expect(stop).not.toHaveBeenCalled();
 });
 it("unlink stops operator-held Goals before link writes and refuses a still-owned session",async()=>{
  const bot=exists(),get=vi.spyOn(store,"getTask").mockReturnValue({...summary() as object,supervisorBotId:botId} as never),read=vi.spyOn(goal,"readGoalLoopState").mockReturnValue({...loop() as object,status:"blocked"} as never),stop=vi.spyOn(harness,"stopBotCodeTask").mockImplementation(async()=>{read.mockReturnValue(null);return summary();}),patchBot=vi.spyOn(bots,"patchBot").mockReturnValue({id:botId} as never),patchTask=vi.spyOn(store,"patchTask").mockReturnValue(summary() as never);vi.spyOn(relay,"isRoomDelegatedCodeTask").mockReturnValue(false);
  expect((await request("code-session","PATCH",{action:"unlink",taskId:"code"})).status).toBe(200);expect(stop.mock.invocationCallOrder[0]).toBeLessThan(patchTask.mock.invocationCallOrder[0]);expect(patchTask).toHaveBeenCalledExactlyOnceWith("code",{supervisorBotId:null});expect(patchBot).toHaveBeenCalledExactlyOnceWith(botId,{codeSessionTaskId:null});
  read.mockReturnValue({...loop() as object,status:"paused"} as never);stop.mockResolvedValueOnce(summary());expect((await request("code-session","PATCH",{action:"unlink",taskId:"code"})).status).toBe(409);expect(patchBot).toHaveBeenCalledOnce();
  get.mockReturnValue(undefined);bot.mockReturnValue({id:botId,codeSessionTaskId:"missing"} as never);expect((await request("code-session","PATCH",{action:"clear",taskId:"missing"})).body.task).toBeNull();
 });
 it("partial unlink writes cannot become a typed safe refusal or be replayed",async()=>{
  exists();vi.spyOn(store,"getTask").mockReturnValue({...summary() as object,supervisorBotId:botId} as never);vi.spyOn(relay,"isRoomDelegatedCodeTask").mockReturnValue(false);vi.spyOn(goal,"readGoalLoopState").mockReturnValue(null);const patch=vi.spyOn(store,"patchTask").mockReturnValue(summary() as never),bot=vi.spyOn(bots,"patchBot").mockImplementation(()=>{throw Object.assign(new Error("PRIVATE after-write"),{status:400});}),id=randomUUID();
  const result=await request("code-session","PATCH",{action:"unlink",taskId:"code"},id);expect(result.status).toBe(503);expect(result.body).toMatchObject({operation:{execution:"unknown"}});expect(JSON.stringify(result.body)).not.toContain("PRIVATE");expect(patch).toHaveBeenCalledExactlyOnceWith("code",{supervisorBotId:null});expect(bot).toHaveBeenCalledOnce();expect((await request("code-session","PATCH",{action:"unlink",taskId:"code"},id)).status).toBe(409);expect(patch).toHaveBeenCalledOnce();
 });
 it("malformed successes/private failures are not fake empty reads and never replay after effect",async()=>{
  exists();vi.spyOn(harness,"getBotCodeSessionPanelState").mockResolvedValue({tasks:[{}],loops:{}} as never);expect((await request()).status).toBe(503);vi.spyOn(relay,"listBotCodeRequests").mockReturnValue([{}] as never);expect((await request("code-requests")).status).toBe(503);const create=vi.spyOn(harness,"createBotCodeTask").mockResolvedValue({} as never),id=randomUUID();expect((await request("code-session","POST",{projectId:null,prompt:"x"},id)).body.operation).toMatchObject({execution:"unknown"});expect((await request("code-session","POST",{},id)).status).toBe(409);expect(create).toHaveBeenCalledOnce();
 });
 it("auth/Origin/bounds/selectors and guarded SDK wrappers refuse before store, SDK or writes",async()=>{
  const get=vi.spyOn(bots,"getBot"),create=vi.spyOn(harness,"createBotCodeTask"),stop=vi.spyOn(harness,"stopBotCodeTask"),peek=vi.spyOn(harness,"peekCodeRequestProgress"),relayStop=vi.spyOn(relay,"stopBotCodeRequest"),before=readdirSync(root);
  for(const action of ["code-session","code-requests"])expect((await request(action,"POST",{},undefined,false)).status).toBe(401);expect((await request("code-session","POST",{},undefined,true,"https://evil.test")).status).toBe(403);expect((await request("code-session","POST","x".repeat(262145))).status).toBe(413);expect((await request("code-requests","POST","x".repeat(4097))).status).toBe(413);expect(readdirSync(root)).toEqual(before);for(const selector of ["invalid","..%2Fx","%252F"])expect((await request("code-session","GET",undefined,undefined,true,undefined,undefined,selector)).status).toBe(400);
  vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");for(const fn of [()=>entrances.createBotCodeTask(botId,{projectId:null,prompt:"x",permissionMode:"ask"}),()=>entrances.continueBotCodeTask(botId,"code","x"),()=>entrances.stopBotCodeTask(botId,"code"),()=>entrances.peekCodeRequestProgress("code"),()=>entrances.getBotCodeSessionPanelState(botId),()=>entrances.abortTaskIncludingColdGoalLoop("code"),()=>entrances.goalLoopCommand("code",{action:"stop"})])expect(fn).toThrow("owned by Backend");await expect(entrances.abortBotCodeRequest(botId,requestId)).rejects.toThrow("owned by Backend");await expect(request()).rejects.toThrow("owned by Backend");for(const spy of [get,create,stop,peek,relayStop])expect(spy).not.toHaveBeenCalled();
 });
});
