import { randomUUID } from "node:crypto";
import { existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import * as bots from "@/lib/bots";
import * as intercom from "@/lib/bot-intercom";
import * as harness from "@/lib/pi/harness";
import * as relay from "@/lib/pi/bot-code-relay";
import { insertTask,patchTask } from "@/lib/store";
import { createRoom,appendRoomMessage } from "@/lib/rooms";
import { dispatchJsonBusinessRequest } from "@backend-runtime/json-business/index";
import { publicJsonBusinessResult } from "@shared/json-business-contract.mjs";
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-bot-overview-"));vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_BACKEND_RUNTIME","attach");vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",join(root,"agent"));intercom.resetBotIntercomForTests();});
afterEach(()=>{intercom.resetBotIntercomForTests();vi.restoreAllMocks();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
async function request(route:string,method="GET",body?:unknown,id=randomUUID(),authorized=true,origin?:string,headers:Record<string,string>={}){const result=await dispatchJsonBusinessRequest({route,method,url:`http://localhost/api/${route}`,headers:{host:"localhost",...(origin?{origin}:{}),...headers},authorized,operationId:method==="GET"?undefined:id,body:body===undefined?undefined:new TextEncoder().encode(typeof body==="string"?body:JSON.stringify(body))});const dto=publicJsonBusinessResult(route,result,method);expect(dto).not.toBeNull();return dto!;}
function seed(){const alice=bots.createBot({name:"Alice 日本語"}),bob=bots.createBot({name:"Bob 日本語"});const now=Date.now(),path=join(root,"bots",bob.id,"intercom","mailbox.json"),message={v:1,id:randomUUID(),fromBotId:alice.id,toBotId:bob.id,text:" authored 日本語 " + "😀".repeat(90),createdAt:now,depth:0,kind:"ask",delivery:"queued",conversationId:randomUUID(),scopeId:"fixture",attachments:[{kind:"file",name:"authored.txt",mimeType:"text/plain",file:"fixture.dat",bytes:4,token:"PRIVATE"}],token:"PRIVATE"};mkdirSync(join(root,"bots",bob.id,"intercom"),{recursive:true});writeFileSync(path,JSON.stringify({v:1,lastReadAt:0,messages:[message],pendingAsks:[{id:message.id,conversationId:message.conversationId,fromBotId:alice.id,toBotId:bob.id,text:message.text,createdAt:now,expiresAt:now+600000,depth:0}]}));return {alice,bob,path,message,route:`bots/${bob.id}/intercom`};}
describe("Bot sidebar/inbox Backend owner",()=>{
 it("reads durable mailbox/pending ask/peer presence; mark-read is owner scoped and ignores forged timestamp/mutations",async()=>{
  const {alice,bob,path,message,route}=seed();intercom.setBotIntercomResidentLookup(id=>id===alice.id);const read=await request(route);expect(read.status).toBe(200);expect(read.body!.inbox).toMatchObject({unreadCount:1,messages:[{id:message.id,fromName:alice.name,attachments:[{file:"fixture.dat"}]}],pendingAsks:[{id:message.id}],peerPresence:{botId:alice.id,status:"online"}});expect(JSON.stringify(read)).not.toContain("PRIVATE");expect(Array.from((read.body!.inbox as {preview:{text:string}}).preview.text).length).toBe(80);expect(existsSync(join(root,"bot-overview-command.json"))).toBe(false);
  const id=randomUUID(),marked=await request(route,"PATCH",{action:"read",botId:alice.id,readAt:1,messages:[],pendingAsks:[]},id);expect(marked.status).toBe(200);expect(marked.body!.inbox).toMatchObject({unreadCount:0,messages:[{id:message.id}],pendingAsks:[{id:message.id}]});const saved=JSON.parse(readFileSync(path,"utf8"));expect(saved.lastReadAt).toBeGreaterThanOrEqual(message.createdAt);expect(saved.messages[0].text).toBe(message.text);expect((await request(route,"PATCH",{action:"read"},id)).status).toBe(409);intercom.resetBotIntercomForTests();expect((await request(route)).body!.inbox).toMatchObject({unreadCount:0,messages:[{id:message.id}],pendingAsks:[{id:message.id}]});expect(existsSync(join(root,"bots",alice.id,"intercom","mailbox.json"))).toBe(false);const ledger=readFileSync(join(root,"bot-overview-command.json"),"utf8");for(const value of [alice.id,bob.id,message.id,"authored","PRIVATE"])expect(ledger).not.toContain(value);
 });
 it("failed persistence invalidates the marker cache instead of reporting false durable read or leaking IO errors",async()=>{
  const {path,route}=seed();expect((await request(route)).body!.inbox).toMatchObject({unreadCount:1});mkdirSync(path+".lock");writeFileSync(join(path+".lock","owner"),"held");const id=randomUUID(),failed=await request(route,"PATCH",{action:"read"},id);expect(failed.status).toBe(503);expect(failed.body).toMatchObject({operation:{execution:"unknown"}});expect(JSON.stringify(failed)).not.toContain("mailbox is busy");expect(JSON.parse(readFileSync(path,"utf8")).lastReadAt).toBe(0);rmSync(path+".lock",{recursive:true,force:true});expect((await request(route)).body!.inbox).toMatchObject({unreadCount:1});expect((await request(route,"PATCH",{action:"read"},id)).status).toBe(409);expect((await request(route,"PATCH",{action:"read"})).status).toBe(200);
 },10000);
 it("a typed event-listener exception after persistence remains unknown and reloads the actual saved marker",async()=>{
  const {bob,path,route}=seed();const unsubscribe=intercom.subscribeBotIntercomInbox(bob.id,()=>{throw Object.assign(new Error("PRIVATE listener/path"),{status:400});});const id=randomUUID(),failed=await request(route,"PATCH",{action:"read"},id);expect(failed.status).toBe(503);expect(failed.body).toMatchObject({operation:{execution:"unknown"}});expect(JSON.stringify(failed)).not.toContain("PRIVATE");expect(JSON.parse(readFileSync(path,"utf8")).lastReadAt).toBeGreaterThan(0);unsubscribe();expect((await request(route)).body!.inbox).toMatchObject({unreadCount:0});expect((await request(route,"PATCH",{action:"read"},id)).status).toBe(409);
 });
 it("sidebar reads offline transcript/Room previews and one outbox batch, counts owned/supervised work, and returns projected ETag/304 without SDK",async()=>{
  const {alice,bob}=seed(),file=join(root,"fixture-transcript.jsonl");writeFileSync(file,JSON.stringify({type:"message",message:{role:"assistant",content:[{type:"text",text:" Fixture answer 日本語 \n"+"😀".repeat(90)}],timestamp:1700000000000}})+"\n");patchTask("bot:"+alice.id,{sessionFile:file});const owned=insertTask({project:null,title:"Owned",providerID:"fixture",modelID:"fixture",thinkingLevel:"off",botId:alice.id}),supervised=insertTask({project:null,title:"Supervised",providerID:"fixture",modelID:"fixture",thinkingLevel:"off"});patchTask(owned.id,{status:"working"});patchTask(supervised.id,{status:"working",supervisorBotId:alice.id});const room=createRoom({name:"Room 日本語",members:[alice.id,bob.id]});appendRoomMessage(room.id,{id:randomUUID(),role:"user",text:"Room authored 日本語",createdAt:1700000000001});const batch=vi.spyOn(relay,"listBotCodeRequestsForBots"),sdk=vi.spyOn(harness,"getTaskDetail"),start=vi.spyOn(harness,"promptTask");const response=await request("bots/sidebar");expect(response.status).toBe(200);const list=response.body!.bots as Record<string,unknown>[];expect(list.find(bot=>bot.id===alice.id)).toMatchObject({codeSessionCount:2,codeInProgress:false,lastMessageAt:new Date(1700000000000).toISOString()});expect(Array.from(list.find(bot=>bot.id===alice.id)!.lastMessageSummary as string)).toHaveLength(80);expect(response.body!.rooms).toMatchObject([{id:room.id,lastMessageSummary:"Room authored 日本語",messages:[{text:"Room authored 日本語"}]}]);expect(batch).toHaveBeenCalledExactlyOnceWith(list.map(bot=>bot.id));const etag=response.headers!.etag;expect(etag).toMatch(/^W\//);expect((await request("bots/sidebar","GET",undefined,undefined,true,undefined,{"if-none-match":etag})).status).toBe(304);expect(sdk).not.toHaveBeenCalled();expect(start).not.toHaveBeenCalled();expect(existsSync(join(root,"bot-overview-command.json"))).toBe(false);
 });
 it("invalid success is rejected even on conditional GET, rather than a fake empty inbox/list or hidden bad DTO",async()=>{
  const {route}=seed();vi.spyOn(intercom,"getBotIntercomInbox").mockReturnValue({} as never);expect((await request(route)).status).toBe(503);vi.spyOn(bots,"listBots").mockReturnValue([{}] as never);expect((await request("bots/sidebar","GET",undefined,undefined,true,undefined,{"if-none-match":"*"})).status).toBe(503);
 });
 it("invalid action/missing Bot/unsafe IDs/auth/Origin/bounds and Next common reads/mark reject before storage/cache/SDK",async()=>{
  const before=readdirSync(root);expect((await request("bots/sidebar","GET",undefined,undefined,false)).status).toBe(401);expect((await request("bots/"+randomUUID()+"/intercom","PATCH",{action:"read"},undefined,true,"https://evil.test")).status).toBe(403);expect((await request("bots/"+randomUUID()+"/intercom","PATCH","x".repeat(4097))).status).toBe(413);expect(readdirSync(root)).toEqual(before);for(const id of ["invalid","..%2Fx","%252F"])expect((await request(`bots/${id}/intercom`)).status).toBe(400);expect((await request("bots/"+randomUUID()+"/intercom")).status).toBe(404);const {bob,route}=seed();for(const value of [{action:"send"},{action:1},true,[],"{" ])expect((await request(route,"PATCH",value)).status).toBe(400);const lookup=vi.spyOn(bots,"getBot"),files=readdirSync(root);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");expect(()=>intercom.getBotIntercomInbox(bob.id)).toThrow("owned by Backend");expect(()=>intercom.markBotIntercomInboxRead(bob.id)).toThrow("owned by Backend");await expect(request("bots/sidebar")).rejects.toThrow("owned by Backend");await expect(request(route,"PATCH",{action:"read"})).rejects.toThrow("owned by Backend");expect(lookup).not.toHaveBeenCalled();expect(readdirSync(root)).toEqual(files);
 });
});
