import { afterEach,expect,it,vi } from "vitest";
import { createBoundedEventWriter,readBoundedEventDiagnostics,serializeBoundedEvent,validateBoundedEvent } from "@backend-runtime/event-stream/bounded-writer";
function make(options:any={}){let writer!:ReturnType<typeof createBoundedEventWriter>;const controller=new AbortController();const body=new ReadableStream<Uint8Array>({start(c){writer=createBoundedEventWriter(c,controller.signal,options);},pull(){writer.pull();},cancel(){writer.close();}},{highWaterMark:0});return{writer,controller,body};}
afterEach(()=>{vi.useRealTimers();expect(readBoundedEventDiagnostics()).toMatchObject({writers:0,queuedBytes:0,queuedFrames:0,heartbeats:0,stallTimers:0});});
it("no demand retains bounded frames and pull emits at most64KiB without reordering",async()=>{const x=make(),reader=x.body.getReader();x.writer.send("snapshot",{text:"x".repeat(150000)});expect(readBoundedEventDiagnostics().queuedBytes).toBeGreaterThan(150000);let text="";while(!text.endsWith("\n\n")||!text.includes("event: snapshot")){const item=await reader.read();expect(item.value!.length).toBeLessThanOrEqual(65536);text+=new TextDecoder().decode(item.value);}expect(text.startsWith(": connected\n\n")).toBe(true);expect(text).toContain('"text":"'+ "x".repeat(150000)+'"');await reader.cancel();});
it("producer writes cannot reset a stalled consumer deadline",async()=>{vi.useFakeTimers();const x=make({stallMs:20,heartbeatMs:5}),off=vi.fn();x.writer.onCleanup(off);await vi.advanceTimersByTimeAsync(21);expect(x.writer.closed).toBe(true);expect(off).toHaveBeenCalledOnce();await x.body.cancel();});
it("consumption resets only the progress deadline and abort disposes cleanup exactly once",async()=>{vi.useFakeTimers();const x=make({stallMs:20}),off=vi.fn();x.writer.onCleanup(off);await vi.advanceTimersByTimeAsync(15);const reader=x.body.getReader();await reader.read();x.writer.send("snapshot",{value:1});await vi.advanceTimersByTimeAsync(15);expect(x.writer.closed).toBe(false);x.controller.abort();await reader.cancel();x.writer.close();expect(off).toHaveBeenCalledOnce();});
it("global16MiB quota includes whole backing frames, not just their unread tails",async()=>{const all=[make(),make(),make()];for(const x of all)x.writer.sendSerialized("snapshot",'"'+"x".repeat(7*1024*1024)+'"');expect(readBoundedEventDiagnostics().queuedBytes).toBeLessThanOrEqual(16*1024*1024);expect(all[2].writer.closed).toBe(true);await Promise.all(all.map(x=>x.body.cancel()));});
it.each([()=>{const x:any={};x.self=x;return x;},()=>({data:"x".repeat(8*1024*1024+1)}),()=>({data:1n})])("malformed/oversized serialization tears down rather than retaining subscriptions",async data=>{const x=make();x.writer.send("snapshot",data());expect(x.writer.closed).toBe(true);await x.body.cancel();});
it("escaping/key/node budgets precede full serialization",()=>{expect(()=>serializeBoundedEvent({data:String.fromCharCode(0).repeat(200)},256)).toThrow();expect(()=>serializeBoundedEvent({["x".repeat(257)]:1},256)).toThrow();const data={data:"日本語"+String.fromCharCode(10,0xd800)};expect(serializeBoundedEvent(data)).toBe(JSON.stringify(data));});
it("non-materializing validation keeps serializer budgets and actual encoded bytes",()=>{
 const valid={data:"日本語"+String.fromCharCode(10,0xd800),date:new Date("2026-01-01"),array:[1,null,undefined]};
 expect(()=>validateBoundedEvent(valid)).not.toThrow();expect(serializeBoundedEvent(valid)).toBe(JSON.stringify(valid));
 for(const bad of[{data:String.fromCharCode(0).repeat(200)},{["x".repeat(257)]:1},{data:1n}]){expect(()=>validateBoundedEvent(bad,256)).toThrow();expect(()=>serializeBoundedEvent(bad,256)).toThrow();}
 const cycle:any={};cycle.self=cycle;expect(()=>validateBoundedEvent(cycle)).toThrow();
 expect(()=>validateBoundedEvent({text:"x".repeat(7*1024*1024)})).not.toThrow();
});
it("tiny frames cannot bypass the per-consumer object count bound",async()=>{const x=make();for(let i=0;i<64;i++)x.writer.send("delta",{});expect(x.writer.closed).toBe(true);expect(readBoundedEventDiagnostics().queuedFrames).toBe(0);await x.body.cancel();});
it("already aborted writers admit no timers and run late cleanup",async()=>{const c=new AbortController();c.abort();const w=createBoundedEventWriter({close(){}} as any,c.signal);const cleanup=vi.fn();w.onCleanup(cleanup);expect(cleanup).toHaveBeenCalledOnce();expect(w.closed).toBe(true);});
