import{afterEach,expect,it,vi}from"vitest";
const deps=vi.hoisted(()=>({detail:vi.fn(),task:vi.fn(()=>()=>{}),inbox:vi.fn(()=>()=>{})}));
vi.mock("@/lib/pi/harness",()=>({subscribeTask:deps.task}));vi.mock("@/lib/pi/get-task-detail-bounded",()=>({getTaskDetailBounded:deps.detail}));vi.mock("@/lib/bot-intercom",()=>({subscribeBotIntercomInbox:deps.inbox,getBotIntercomInbox:()=>({})}));
import{createIndividualWriter,bufferIndividualPending,readIndividualDiagnostics,readIndividualDetail,runIndividualScope}from"@backend-runtime/event-stream/individual-state";
afterEach(()=>{expect(readIndividualDiagnostics()).toMatchObject({individualReads:0,individualWaiters:0,individualPendingBytes:0});});
function writer(){const c=new AbortController();let out!:ReturnType<typeof createIndividualWriter>;const stream=new ReadableStream<Uint8Array>({start(controller){out=createIndividualWriter(controller,{signal:c.signal});},pull(){out.pull();},cancel(){out.close();}},{highWaterMark:0});return{out,c,stream};}
it("ready buffers coalesce cumulatives, cap 64 distinct controls/deltas and release on abort",()=>{const w=writer(),pending:Record<string,unknown>[]=[];for(let i=0;i<100;i++)bufferIndividualPending(pending,{type:"delta",message:{id:"same",text:String(i)}},w.out);expect(pending).toHaveLength(1);for(let i=0;i<65;i++)bufferIndividualPending(pending,{type:"delta",message:{id:"other"+i,text:"x"}},w.out);expect(w.out.closed).toBe(true);expect(pending).toHaveLength(0);const again=writer(),p:Record<string,unknown>[]=[];bufferIndividualPending(p,{type:"snapshot",eventType:"permission_request",permissionRequest:{id:"r"}},again.out);again.c.abort();expect(p).toHaveLength(0);});
it("aggregate pending budget and oversized strings close without unbounded serialization",()=>{const all=Array.from({length:4},writer);try{for(const w of all){const p:Record<string,unknown>[]=[];bufferIndividualPending(p,{type:"delta",message:{id:"m",text:"x".repeat(5*1024*1024)}},w.out);}expect(all.at(-1)!.out.closed).toBe(true);expect(readIndividualDiagnostics().individualPendingBytes).toBeLessThanOrEqual(16*1024*1024);const big=writer();expect(big.out.validate({text:"x".repeat(9*1024*1024)})).toBe(false);expect(big.out.closed).toBe(true);}finally{for(const w of all)w.c.abort();}});
it("two snapshot readers; queued disconnect cannot create another SDK read",async()=>{let finish!:()=>void;const done=new Promise<void>(r=>finish=r);deps.detail.mockImplementation(async()=>{await done;return{messages:[]};});const a=new AbortController(),b=new AbortController(),c=new AbortController();const first=runIndividualScope(a.signal,()=>readIndividualDetail("a")),second=runIndividualScope(b.signal,()=>readIndividualDetail("b")),third=runIndividualScope(c.signal,()=>readIndividualDetail("c"));expect(readIndividualDiagnostics()).toMatchObject({individualReads:2,individualWaiters:1});c.abort();await expect(third).rejects.toThrow("closed");expect(deps.detail).toHaveBeenCalledTimes(2);finish();await Promise.all([first,second]);expect(deps.detail).toHaveBeenCalledWith("a",{readOnly:true});});
