import { afterEach,beforeEach,expect,it,vi } from "vitest";
const deps=vi.hoisted(()=>({room:vi.fn(),read:vi.fn(),task:vi.fn(),code:vi.fn(),routine:vi.fn(),dirty:vi.fn(),pending:vi.fn(),linked:vi.fn()}));
vi.mock("@/lib/rooms",()=>({subscribeRoom:deps.room,roomBotTaskId:(r:string,b:string)=>"room:"+r+":"+b}));
vi.mock("@/lib/pi/harness",()=>({subscribeTask:deps.task,subscribeBotCodeSession:deps.code,subscribeTaskDirty:deps.dirty,linkedCodeTaskIdsForOrigin:deps.linked,pendingPermissionForTask:deps.pending,pendingQuestionForTask:()=>null}));
vi.mock("@/lib/routines",()=>({subscribeRoutineRuns:deps.routine}));
vi.mock("@backend-runtime/file-stream/room-attachments",()=>({readRoomStreamSnapshot:deps.read,readRoomAttachmentDiagnostics:()=>({metadataActive:0,metadataQueued:0})}));
import { openLiveEvents,readLiveEventDiagnostics } from "@backend-runtime/event-stream/index";
const id="11111111-1111-4111-8111-111111111111";let room:any,roomListener:()=>void,taskListeners:Map<string,(p:any)=>void>,codeListener:(p:any)=>void,routineListener:(p:any)=>void,dirtyListener:(p:any)=>void;const offs:Array<ReturnType<typeof vi.fn>>=[];
const open=(route="bots/rooms/"+id+"/events",extra:any={})=>openLiveEvents({route,method:"GET",url:"http://localhost/api/"+route,authorized:true,signal:new AbortController().signal,...extra});
beforeEach(()=>{vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_WEBUI_AUTH","required");room={id,name:"fixture",members:["b"],createdAt:"1",updatedAt:"1",messages:[{id:"m",role:"user",text:"fixture".repeat(100),createdAt:1}]};taskListeners=new Map();offs.length=0;for(const fn of Object.values(deps))fn.mockReset();const off=()=>{const fn=vi.fn();offs.push(fn);return fn;};deps.read.mockImplementation(async()=>structuredClone(room));deps.room.mockImplementation((_id,fn)=>{roomListener=fn;return off();});deps.task.mockImplementation((id,fn)=>{taskListeners.set(id,fn);return off();});deps.code.mockImplementation(fn=>{codeListener=fn;return off();});deps.routine.mockImplementation(fn=>{routineListener=fn;return off();});deps.dirty.mockImplementation(fn=>{dirtyListener=fn;return off();});deps.linked.mockReturnValue(["code:child"]);deps.pending.mockReturnValue(null);});
afterEach(async()=>{await vi.waitFor(()=>expect(readLiveEventDiagnostics()).toMatchObject({active:0,subscriptions:0,pollTimers:0,pendingReads:0,writers:0,queuedBytes:0,heartbeats:0,stallTimers:0,retainedSnapshotBytes:0}));vi.unstubAllEnvs();});
async function frame(reader:ReadableStreamDefaultReader<Uint8Array>,event="snapshot"){let text="";while(!text.includes("event: "+event)||!text.endsWith("\n\n")){const part=await reader.read();expect(part.done).toBe(false);text+=new TextDecoder().decode(part.value);}return JSON.parse(text.slice(text.lastIndexOf("data: ")+6).trim());}
it("Room bootstrap/delta/reset, attention-only reuse and reconnect preserve the public contract",async()=>{const response=await open(),reader=response.body!.getReader();expect((await frame(reader)).room.messages).toEqual(room.messages);room.messages.push({id:"n",role:"assistant",text:"next",createdAt:2});room.updatedAt="2";roomListener();expect((await frame(reader)).roomMessagesDelta).toEqual([room.messages[1]]);deps.pending.mockReturnValue({id:"permission"});taskListeners.get("code:child")!({type:"snapshot"});expect(await frame(reader)).toMatchObject({roomReused:true,attention:[{permission:{id:"permission"}}]});room.messages=[];room.updatedAt="3";roomListener();expect((await frame(reader)).room.messages).toEqual([]);await reader.cancel();const again=await open(),r=again.body!.getReader();expect((await frame(r)).room.messages).toEqual([]);await r.cancel();for(const off of offs)expect(off).toHaveBeenCalledOnce();});
it("global Bot Code and routine events pass through without opening sessions",async()=>{const response=await open("bots/events"),reader=response.body!.getReader();codeListener({type:"snapshot",eventType:"code_complete",taskId:"code:c"});expect(await frame(reader)).toMatchObject({eventType:"code_complete"});routineListener({botId:"b",runId:"r",status:"done"});expect(await frame(reader,"routine")).toMatchObject({runId:"r"});dirtyListener({taskId:"t",reason:"permission"});expect(await frame(reader,"task_dirty")).toEqual({taskId:"t",reason:"permission"});await reader.cancel();expect(deps.read).not.toHaveBeenCalled();});
it("authorization/id/method/role/preabort precede all subscriptions and reads",async()=>{expect((await open(undefined,{authorized:false})).status).toBe(401);expect((await open("bots/rooms/%2e%2e/events")).status).toBe(404);expect((await open(undefined,{method:"POST"})).status).toBe(405);const c=new AbortController();c.abort();expect((await open(undefined,{signal:c.signal})).status).toBe(400);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");await expect(open()).rejects.toThrow(/owned by Backend/);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");expect(deps.read).not.toHaveBeenCalled();expect(deps.task).not.toHaveBeenCalled();});
it("subscription failures, deletion and cancellation after async read leave no timers",async()=>{deps.task.mockImplementationOnce(()=>{throw new Error("PRIVATE");});const failed=await open();await failed.body!.cancel();deps.read.mockRejectedValueOnce(Object.assign(new Error("deleted"),{code:"ENOENT"}));expect((await open()).status).toBe(404);const c=new AbortController();deps.read.mockImplementationOnce(async()=>{c.abort();return room;});expect((await open(undefined,{signal:c.signal})).status).toBe(400);});
it("member/linked-task floods and metadata limit fail closed without retaining sessions",async()=>{deps.linked.mockReturnValue(Array.from({length:130},(_,i)=>"c"+i));const response=await open();await response.body!.cancel();expect(deps.task).not.toHaveBeenCalled();deps.read.mockRejectedValueOnce(new Error("Room metadata limit"));expect((await open()).status).toBe(503);});
it("32-reader admission and repeated consumer cancellation release every lifecycle bus",async()=>{const all=await Promise.all(Array.from({length:32},()=>open("bots/events")));expect((await open("bots/events")).status).toBe(503);await Promise.all(all.map(r=>r.body!.cancel()));});
