import {randomUUID} from "node:crypto";
import {mkdirSync,mkdtempSync,readFileSync,readdirSync,rmSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";import {join} from "node:path";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import * as rooms from "@/lib/rooms";import * as relay from "@/lib/pi/bot-code-relay";import * as prompt from "@/lib/room-prompt";
import {revertRoomComposer,revertRoomConversation} from "@backend-runtime/lib/room-revert";import {abortRoomCodeRequest} from "@backend-runtime/lib/room-code";
import {dispatchJsonBusinessRequest} from "@backend-runtime/json-business/index";import {publicJsonBusinessResult} from "@shared/json-business-contract.mjs";
let root:string;beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-room-command-"));vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_BACKEND_RUNTIME","attach");vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",join(root,"agent"));});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
async function request(roomId:string,action:string,body:unknown,id=randomUUID(),authorized=true,origin?:string,signal?:AbortSignal){const route=`bots/rooms/${roomId}/${action}`,result=await dispatchJsonBusinessRequest({route,method:"POST",url:"http://localhost/api/"+route,headers:{host:"localhost",...(origin?{origin}:{})},authorized,operationId:id,signal,body:new TextEncoder().encode(typeof body==="string"?body:JSON.stringify(body))});const dto=publicJsonBusinessResult(route,result,"POST");expect(dto).not.toBeNull();return dto!;}
function outbox(roomId:string,id:string){mkdirSync(join(root,"bot-code-requests"),{recursive:true});const value={id,botId:"fixture-owner",originTaskId:"fixture-origin",codeTaskId:null,state:"queued",queuedAt:Date.now(),prompt:"Authored",baseline:null,room:{id:roomId,conversation:{requestId:"fixture-user",participantIds:[],turn:1,maxTurns:1},responseId:"fixture-response"}};writeFileSync(join(root,"bot-code-requests",id+".json"),JSON.stringify(value));return value;}
describe("Room conversation owner",()=>{
 it("persists authored attachments once and rehydrates composer only in Backend; ledger retains no inputs",async()=>{const room=rooms.createRoom({}),id=randomUUID(),data=Buffer.from("Authored 日本語").toString("base64");const result=await request(room.id,"prompt",{prompt:"Edit 日本語",broadcast:true,files:[{name:"authored 日本語.txt",mimeType:"text/plain",data}],images:[{mimeType:"image/png",data:"YQ=="}],botId:"FORGED",messageId:"FORGED",codeTaskId:"FORGED"},id);expect(result.status).toBe(200);expect(result.body).toMatchObject({routedBotIds:[],room:{messages:[{text:"Edit 日本語",files:[{name:"authored 日本語.txt"}]}]}});const message=rooms.getRoom(room.id)!.messages[0];expect((await request(room.id,"prompt",{prompt:"again"},id)).status).toBe(409);expect(rooms.getRoom(room.id)?.messages).toHaveLength(1);const reverted=await request(room.id,"revert",{messageId:message.id});expect(reverted.status).toBe(200);expect(reverted.body).toMatchObject({text:"Edit 日本語",room:{messages:[]},images:[{uri:"data:image/png;base64,YQ=="}],files:[{name:"authored 日本語.txt",uri:"data:text/plain;base64,"+data}]});const ledger=readFileSync(join(root,"room-conversation-command.json"),"utf8");for(const value of [room.id,message.id,data,"日本語","FORGED"])expect(ledger).not.toContain(value);});
 it("explicit Code selection is confined to this Room and never falls back to sibling/1:1 work",async()=>{const room=rooms.createRoom({}),other=rooms.createRoom({}),own="c".repeat(64),foreign="d".repeat(64);outbox(room.id,own);outbox(other.id,foreign);expect((await request(room.id,"code",{action:"abort",requestId:foreign})).status).toBe(404);expect((await request(room.id,"code",{action:"abort",requestId:own,botId:"forged",codeTaskId:"forged"})).status).toBe(200);expect(JSON.parse(readFileSync(join(root,"bot-code-requests",own+".json"),"utf8"))).toMatchObject({state:"cancelled",stoppedByUser:true});expect(JSON.parse(readFileSync(join(root,"bot-code-requests",foreign+".json"),"utf8")).state).toBe("queued");});
 it("concurrent admission allows Code stop while prompt preparation waits; disconnect does not cancel accepted work",async()=>{const room=rooms.createRoom({}),own="e".repeat(64);outbox(room.id,own);let release!:(v:Awaited<ReturnType<typeof prompt.handleRoomPrompt>>)=>void;const stub=vi.spyOn(prompt,"handleRoomPrompt").mockImplementation(()=>new Promise(resolve=>{release=resolve;}));const control=new AbortController(),pending=request(room.id,"prompt",{prompt:"accepted"},undefined,true,undefined,control.signal);await vi.waitFor(()=>expect(stub).toHaveBeenCalled());control.abort();expect((await request(room.id,"code",{action:"abort",requestId:own})).status).toBe(200);release({status:200,body:{room:rooms.getRoom(room.id),routedBotIds:[]}});expect((await pending).status).toBe(200);});
 it("post-append event and post-rewind typed cancel failures are unknown with actual saved state",async()=>{const room=rooms.createRoom({}),off=rooms.subscribeRoom(room.id,()=>{throw Object.assign(new Error("PRIVATE/path"),{status:400});});const id=randomUUID(),failed=await request(room.id,"prompt",{prompt:"Saved"},id);off();expect(failed.status).toBe(503);expect(failed.body).toMatchObject({operation:{execution:"unknown"}});expect(JSON.stringify(failed)).not.toContain("PRIVATE");const target=rooms.getRoom(room.id)!.messages[0];expect(target.text).toBe("Saved");expect((await request(room.id,"prompt",{prompt:"again"},id)).status).toBe(409);vi.spyOn(relay,"cancelRoomCodeRequests").mockRejectedValueOnce(Object.assign(new Error("PRIVATE"),{status:404}));const rewind=await request(room.id,"revert",{messageId:target.id});expect(rewind.status).toBe(503);expect(rewind.body).toMatchObject({operation:{execution:"unknown"}});expect(rooms.getRoom(room.id)?.messages).toEqual([]);});
 it("invalid selectors/input/auth/Origin/bounds and malformed success refuse without fallback",async()=>{const before=readdirSync(root);expect((await request(randomUUID(),"prompt",{},undefined,false)).status).toBe(401);expect((await request(randomUUID(),"prompt",{},undefined,true,"https://evil.test")).status).toBe(403);expect((await request(randomUUID(),"code","x".repeat(4097))).status).toBe(413);expect(readdirSync(root)).toEqual(before);for(const id of ["bad","..%2Fx","%252F"])expect((await request(id,"prompt",{prompt:"x"})).status).toBe(400);const room=rooms.createRoom({});for(const body of [[],null,{prompt:1},{prompt:"x",fromBot:true},{prompt:"x",files:[{name:"x",mimeType:"text/plain",data:"/w=="}]}])expect((await request(room.id,"prompt",body)).status).toBeGreaterThanOrEqual(400);expect(rooms.getRoom(room.id)?.messages).toEqual([]);vi.spyOn(prompt,"handleRoomPrompt").mockResolvedValue({status:200,body:{room:{},routedBotIds:[]}});expect((await request(room.id,"prompt",{prompt:"x"})).status).toBe(503);});
 it("Next refuses common commands and attachment/relay mutations before access",async()=>{const room=rooms.createRoom({}),files=readdirSync(root);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");for(const call of [()=>prompt.handleRoomPrompt(room.id,{prompt:"x"}),()=>revertRoomConversation(room.id,"x"),()=>revertRoomComposer(room.id,"x"),()=>abortRoomCodeRequest(room.id)])await expect(call()).rejects.toThrow("owned by Backend");for(const call of [()=>rooms.saveRoomFiles(room.id,"x",[]),()=>rooms.saveRoomImages(room.id,"x",[]),()=>rooms.consumeRoomRelayEnvelope(room.id,"x"),()=>rooms.revertRoomTo(room.id,"x")])expect(call).toThrow("owned by Backend");expect(readdirSync(root)).toEqual(files);});
});
