import { randomUUID } from "node:crypto";
import { mkdtempSync,readdirSync,readFileSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import * as rooms from "@/lib/rooms";
import { createBot } from "@/lib/bots";
import * as owner from "@backend-runtime/lib/room-lifecycle-api";
import { dispatchJsonBusinessRequest } from "@backend-runtime/json-business/index";
import { publicJsonBusinessResult } from "@shared/json-business-contract.mjs";
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-room-owner-"));vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_BACKEND_RUNTIME","attach");vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",join(root,"agent"));});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
async function request(route:string,method="GET",body?:unknown,id=randomUUID(),authorized=true,origin?:string){const result=await dispatchJsonBusinessRequest({route,method,url:`http://localhost/api/${route}`,headers:{host:"localhost",...(origin?{origin}:{})},authorized,operationId:method==="GET"?undefined:id,body:body===undefined?undefined:new TextEncoder().encode(typeof body==="string"?body:JSON.stringify(body))});const dto=publicJsonBusinessResult(route,result,method);expect(dto).not.toBeNull();return dto!;}
describe("Room lifecycle Backend owner",()=>{
 it("CRUD preserves authored names/known deduplicated members, ignores caller identity/privilege/history, and durably refuses replay",async()=>{const bot=createBot({name:"Member 日本語"}),id=randomUUID(),created=await request("bots/rooms","POST",{name:" Room 日本語 ",members:[bot.id,bot.id,randomUUID()],id:"FORGED",botRelayEnabled:true,codeAutoApprove:true,messages:[{text:"FORGED"}]},id);expect(created.status).toBe(201);const room=created.body!.room as {id:string};expect(room).toMatchObject({name:"Room 日本語",members:[bot.id],botRelayEnabled:false,messages:[]});expect(room.id).not.toBe("FORGED");expect(room).not.toHaveProperty("codeAutoApprove");expect((await request("bots/rooms")).body!.rooms).toMatchObject([{id:room.id}]);const path="bots/rooms/"+room.id;expect((await request(path)).body!.room).toMatchObject({id:room.id});expect((await request(path,"PATCH",{name:"Renamed 日本語",id:"FORGED",messages:[]})).status).toBe(200);expect(rooms.getRoom(room.id)?.name).toBe("Renamed 日本語");expect((await request("bots/rooms","POST",{},id)).status).toBe(409);expect((await request(path,"DELETE")).status).toBe(200);expect((await request(path)).status).toBe(404);const ledger=readFileSync(join(root,"room-lifecycle-command.json"),"utf8");for(const privateValue of ["日本語",bot.id,room.id,"FORGED"])expect(ledger).not.toContain(privateValue);});
 it("invalid success is 503, not empty/history-less success; admitted event failure is unknown with actual saved state",async()=>{const room=rooms.createRoom({name:"Original"}),path="bots/rooms/"+room.id;const unsubscribe=rooms.subscribeRoom(room.id,()=>{throw Object.assign(new Error("PRIVATE event/credential/path"),{status:400});});const id=randomUUID(),result=await request(path,"PATCH",{name:"Saved 日本語"},id);expect(result.status).toBe(503);expect(result.body).toMatchObject({operation:{execution:"unknown"}});expect(JSON.stringify(result)).not.toContain("PRIVATE");unsubscribe();expect((await request(path)).body!.room).toMatchObject({name:"Saved 日本語"});expect((await request(path,"PATCH",{},id)).status).toBe(409);vi.spyOn(owner,"listRoomConfiguration").mockReturnValue({rooms:[{}]} as never);expect((await request("bots/rooms")).status).toBe(503);});
 it("read is ledger-free; invalid IDs decode only once and auth/Origin/bounds refuse before storage",async()=>{const before=readdirSync(root);expect((await request("bots/rooms","GET",undefined,undefined,false)).status).toBe(401);expect((await request("bots/rooms","POST",{},undefined,true,"https://evil.test")).status).toBe(403);expect((await request("bots/rooms","POST","x".repeat(65537))).status).toBe(413);expect((await request("bots/rooms/"+randomUUID(),"DELETE","x".repeat(4097))).status).toBe(413);expect(readdirSync(root)).toEqual(before);for(const id of ["rooms","..%2Fx","%252F","bad"]){expect((await request("bots/rooms/"+id)).status).toBe(400);}expect((await request("bots/rooms")).body!.rooms).toEqual([]);expect(readdirSync(root)).toEqual(before);});
 it("Next common lifecycle entrypoints reject before room/cache/files/SDK access",async()=>{const room=rooms.createRoom({}),files=readdirSync(root);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");for(const call of [()=>owner.listRoomConfiguration(),()=>owner.readRoomConfiguration(room.id),()=>owner.createRoomConfiguration({}),()=>rooms.createRoom({}),()=>rooms.patchRoom(room.id,{}),()=>rooms.deleteRoom(room.id)])expect(call).toThrow("owned by Backend");await expect(request("bots/rooms")).rejects.toThrow("owned by Backend");await expect(request("bots/rooms/"+room.id,"PATCH",{})).rejects.toThrow("owned by Backend");expect(readdirSync(root)).toEqual(files);});
});
