import type { UiMessage } from "@/lib/types";

const messageFingerprintCache = new WeakMap<object, string>();
const messageContentFingerprintCache = new WeakMap<object, string>();

function messageFingerprint(message: object): string {
  // SSE DTOs are immutable; cache fingerprints so the previous delta is not serialized again.
  const cached = messageFingerprintCache.get(message);
  if (cached !== undefined) return cached;
  const fingerprint = JSON.stringify(message);
  messageFingerprintCache.set(message, fingerprint);
  return fingerprint;
}

/**
 * Identify one projected message without ids generated by the projection layer.
 * Keep createdAt so two identical prompts from different turns stay separate.
 */
function messageContentFingerprint(message: UiMessage): string {
  const cached = messageContentFingerprintCache.get(message);
  if (cached !== undefined) return cached;
  const fingerprint = JSON.stringify({
    role: message.role,
    createdAt: message.createdAt,
    goalLoopTurn: message.goalLoopTurn,
    intercom: message.intercom,
    hangRetry: message.hangRetry,
    fromBot: message.fromBot,
    parts: message.parts.map(
      // eslint-disable-next-line @typescript-eslint/no-unused-vars -- projection-layer ids are intentionally stripped from the fingerprint
      ({ id: _id, ...part }) => part,
    ),
  });
  messageContentFingerprintCache.set(message, fingerprint);
  return fingerprint;
}

/**
 * Keep a timeline row mounted while a streamed message receives its persisted
 * entry id. Part ids are derived before that id is assigned and remain stable.
 */
export function messageRenderKey(message: UiMessage): string {
  const firstPartId = message.parts[0]?.id;
  return firstPartId ? `part:${firstPartId}` : `message:${message.id}`;
}

/**
 * Remove duplicate rows left when a streamed message is re-identified.
 * Either side can change: the entry id is assigned on persist, and part ids are
 * derived from the raw session index, so match on both keys.
 * Diagnostics flags a message whose keys point to different output rows.
 */
export function dedupeUiMessages(
  messages: UiMessage[],
  diagnostics?: { hasCrossKeyCollision: boolean },
): UiMessage[] {
  if (diagnostics) diagnostics.hasCrossKeyCollision = false;
  if (messages.length < 2) return messages;
  const result: UiMessage[] = [];
  const indexByPartId = new Map<string, number>();
  const indexById = new Map<string, number>();
  const indexByContent = new Map<string, number>();
  let changed = false;
  for (const message of messages) {
    const partId = message.parts[0]?.id;
    const content = messageContentFingerprint(message);
    const existing =
      (partId ? indexByPartId.get(partId) : undefined) ??
      indexById.get(message.id) ??
      indexByContent.get(content);
    const index = existing ?? result.length;
    if (diagnostics && existing !== undefined) {
      const idIndex = indexById.get(message.id);
      const contentIndex = indexByContent.get(content);
      if ((idIndex !== undefined && idIndex !== existing) ||
          (contentIndex !== undefined && contentIndex !== existing)) {
        diagnostics.hasCrossKeyCollision = true;
      }
    }
    if (existing === undefined) {
      result.push(message);
    } else {
      result[existing] = message;
      changed = true;
    }
    if (partId) indexByPartId.set(partId, index);
    indexById.set(message.id, index);
    indexByContent.set(content, index);
  }
  return changed ? result : messages;
}

/**
 * Reuse previous list item references when content is unchanged so
 * memoized rows and scroll contentKey stay stable across SSE floods.
 */
export function stabilizeIdentifiedList<T extends { id: string }>(prev: T[], next: T[]): T[] {
  if (next.length === 0) return next;
  if (prev.length === 0) return next;
  // Snapshots normally keep the same order; avoid building an id map and output array.
  if (prev.length === next.length && prev.every((item, index) => item.id === next[index]?.id)) {
    let out: T[] | undefined;
    for (let index = 0; index < next.length; index++) {
      const old = prev[index]!;
      const message = next[index]!;
      const unchanged = old === message || messageFingerprint(old) === messageFingerprint(message);
      if (!unchanged && !out) out = prev.slice(0, index);
      if (out) out.push(unchanged ? old : message);
    }
    return out ?? prev;
  }
  const prevById = new Map(prev.map((message) => [message.id, message]));
  let changed = prev.length !== next.length;
  const out = next.map((message, index) => {
    const old = prevById.get(message.id);
    if (!old) {
      changed = true;
      return message;
    }
    if (old === message || messageFingerprint(old) === messageFingerprint(message)) {
      if (prev[index] !== old) changed = true;
      return old;
    }
    changed = true;
    return message;
  });
  return changed ? out : prev;
}

/**
 * Reuse previous message object references when content is unchanged so
 * memoized PartView rows skip re-render during SSE floods.
 */
export function stabilizeUiMessages(prev: UiMessage[], next: UiMessage[]): UiMessage[] {
  return stabilizeIdentifiedList(prev, dedupeUiMessages(next));
}

/** Upsert the one message carried by a high-frequency SSE delta. */
export function upsertUiMessage(prev: UiMessage[], next: UiMessage): UiMessage[] {
  const lastIndex = prev.length - 1;
  let existingIndex = prev[lastIndex]?.id === next.id ? lastIndex : -1;
  if (existingIndex < 0) {
    const firstPartId = next.parts[0]?.id;
    const contentKey = messageContentFingerprint(next);
    const last = prev[lastIndex];
    existingIndex = last && (
      (firstPartId && last.parts[0]?.id === firstPartId) || messageContentFingerprint(last) === contentKey
    )
      ? lastIndex
      : prev.findIndex(
          (message) =>
            message.id === next.id ||
            (firstPartId && message.parts[0]?.id === firstPartId) ||
            messageContentFingerprint(message) === contentKey,
        );
  }
  if (existingIndex < 0) return [...prev, next];
  const existing = prev[existingIndex]!;
  if (existing === next || messageFingerprint(existing) === messageFingerprint(next)) return prev;
  const result = prev.slice();
  result[existingIndex] = next;
  return result;
}
