import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { dispatchJsonBusinessRequest } from "@backend-runtime/json-business/index";
import { publicJsonBusinessResult } from "@shared/json-business-contract.mjs";
import { insertTask, patchTask, getTask, upsertProject, patchProject } from "@/lib/store";
import * as owner from "@backend-runtime/lib/task-lifecycle";
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-task-lifecycle-"));vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",join(root,"agent"));});
afterEach(()=>{vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
async function request(path:string,method="GET",query="",body?:unknown,id=method==="GET"?undefined:randomUUID()){
 const result=await dispatchJsonBusinessRequest({route:path,method,url:`http://localhost/api/${path}${query}`,headers:{host:"localhost"},authorized:true,operationId:id,...(body===undefined?{}:{body:new TextEncoder().encode(JSON.stringify(body))})});
 const projected=publicJsonBusinessResult(path,result);expect(projected).not.toBeNull();return {...projected!,body:projected!.body!};
}
function archived(){const task=insertTask({project:null,title:"Transcript"});const sessionFile=join(root,`${task.id}.jsonl`);writeFileSync(sessionFile,[JSON.stringify({type:"session",version:3,id:randomUUID(),cwd:root,timestamp:new Date().toISOString()}),...Array.from({length:205},(_,i)=>JSON.stringify({type:"message",id:`u${i}`,parentId:i?`u${i-1}`:null,timestamp:new Date().toISOString(),message:{role:"user",content:[{type:"text",text:`line ${i}`}],timestamp:i}}))].join("\n")+"\n","utf8");patchTask(task.id,{status:"archived",sessionFile});return {task,sessionFile};}
describe("individual Task Backend owner",()=>{
 it("reads a real archived transcript, owner page/omit modes and ETag without session generation",async()=>{const {task}=archived();const path=`tasks/${task.id}`;const full=await request(path);expect(full.status).toBe(200);expect((full.body.task as {messages:unknown[]}).messages).toHaveLength(205);const page=await request(path,"GET","?messages=page");expect((page.body.task as {messageHistory:{hasMore:boolean}}).messageHistory.hasMore).toBe(true);expect((await request(path,"GET","?messages=omit")).body.task).toMatchObject({messages:[],isStreaming:false});const etag=full.headers.etag;const conditional=await dispatchJsonBusinessRequest({route:path,method:"GET",url:`http://localhost/api/${path}`,headers:{host:"localhost","if-none-match":etag},authorized:true});expect(conditional.status).toBe(304);});
 it("restore/abort/archive/hard delete use the shared Task queue and preserve the transcript file",async()=>{const {task,sessionFile}=archived(),path=`tasks/${task.id}`,id=randomUUID();const restored=await request(path,"PATCH","",{archived:false},id);expect(restored.body).toMatchObject({task:{status:"idle"},operation:{id,execution:"complete"}});expect((await request(path,"PATCH","",{archived:false},id)).status).toBe(409);expect((await request(`${path}/abort`,"POST")).status).toBe(200);expect((await request(path,"DELETE")).body.task).toMatchObject({status:"archived"});expect((await request(path,"DELETE","?hard=1")).body.ok).toBe(true);expect(getTask(task.id)).toBeUndefined();expect(readFileSync(sessionFile,"utf8")).toContain("line 204");expect(readFileSync(join(root,"task-collection-command.json"),"utf8")).not.toContain(sessionFile);});
 it("refuses archived-project restore, missing/archived abort and unsafe/double-encoded IDs",async()=>{const project=upsertProject({name:"archived",rootPath:root});const task=insertTask({project,title:"locked"});patchTask(task.id,{status:"archived"});patchProject(project.id,{archived:true});expect((await request(`tasks/${task.id}`,"PATCH","",{archived:false})).status).toBe(409);expect((await request(`tasks/${task.id}/abort`,"POST")).status).toBe(404);expect((await request("tasks/missing")).status).toBe(404);for(const path of ["tasks/..%2Fx","tasks/%252F"])expect((await request(path)).status).toBe(400);expect(getTask(task.id)?.status).toBe("archived");});
 it("cold active detail is read-only and leaves the task record unchanged without a model/session",async()=>{const {task}=archived();patchTask(task.id,{status:"idle"});const before=getTask(task.id);const detail=await request(`tasks/${task.id}`);expect(detail.status).toBe(200);expect((detail.body.task as {messages:unknown[]}).messages).toHaveLength(205);expect(getTask(task.id)).toEqual(before);});
 it("Next cannot hydrate, mutate rows or stop cold Goal/Bot work before admission",async()=>{const {task}=archived();const before=readdirSync(root);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");for(const action of [()=>owner.getTaskDetail(task.id),()=>owner.restoreTask(task.id),()=>owner.archiveTask(task.id),()=>owner.destroyTask(task.id),()=>owner.abortTaskIncludingColdGoalLoop(task.id),()=>owner.stopBotCodeTask("bot",task.id)])expect(action).toThrow("owned by Backend");await expect(request(`tasks/${task.id}`,"DELETE")).rejects.toThrow("owned by Backend");expect(readdirSync(root)).toEqual(before);});
});
