import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { dispatchJsonBusinessRequest } from "@backend-runtime/json-business/index";
import { publicJsonBusinessResult } from "@shared/json-business-contract.mjs";
import { insertTask, patchTask, getTask } from "@/lib/store";
import { getSetting, setSetting } from "@/lib/pi/web-settings";
import * as harness from "@/lib/pi/harness";
import * as marker from "@/lib/pi/goal-loop-auto-model";
import * as owner from "@backend-runtime/lib/task-execution-settings";
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-task-settings-"));vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",join(root,"agent"));});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
async function request(path:string,body:unknown,method="POST",id=randomUUID(),authorized=true,origin?:string){
 const result=await dispatchJsonBusinessRequest({route:path,method,url:`http://localhost/api/${path}`,headers:{host:"localhost",...(origin?{origin}:{})},authorized,operationId:id,body:new TextEncoder().encode(typeof body==="string"?body:JSON.stringify(body))});
 const dto=publicJsonBusinessResult(path,result);expect(dto).not.toBeNull();return {...dto!,body:dto!.body!};
}
function goalTask(){const task=insertTask({project:null,title:"Settings",providerID:"old",modelID:"old"});patchTask(task.id,{sessionId:"settings-session"});mkdirSync(join(root,"goals-loop"));writeFileSync(join(root,"goals-loop","settings-session.json"),JSON.stringify({sessionId:"settings-session",goal:"fixture",status:"paused",pauseReason:"user",createdAt:"stamp",maxTurns:2,cooldownSeconds:0}));return task;}
describe("Task execution settings Backend owner",()=>{
 it("explicit model selection preserves the SDK/account choice and clears Auto only after success",async()=>{const task=goalTask();await request(`tasks/${task.id}/goal-loop-auto-model`,{enabled:true},"PUT");const spy=vi.spyOn(harness,"setTaskModel").mockImplementation(async(id)=>({...patchTask(id,{providerID:"provider",modelID:"selected",accountId:"pin",accountIdExplicit:true})!,credentials:"PRIVATE"}));const id=randomUUID(),path=`tasks/${task.id}/model`;const selected=await request(path,{model:"pin::provider::selected"},"POST",id);expect(selected.body).toMatchObject({task:{modelID:"selected",accountId:"pin",accountIdExplicit:true},operation:{id,execution:"complete"}});expect(JSON.stringify(selected.body)).not.toContain("PRIVATE");expect(getSetting(`goal-loop-auto-model:${task.id}`)).toBeNull();expect(spy).toHaveBeenCalledWith(task.id,"pin::provider::selected");expect((await request(path,{model:"pin::provider::selected"},"POST",id)).status).toBe(409);expect(spy).toHaveBeenCalledTimes(1);});
 it("failed model leaves Auto intact; failure clearing after the SDK update is unknown without rollback/replay",async()=>{const task=goalTask(),key=`goal-loop-auto-model:${task.id}`,path=`tasks/${task.id}/model`;setSetting(key,"stamp");const spy=vi.spyOn(harness,"setTaskModel").mockRejectedValueOnce(Object.assign(new Error("missing"),{status:400}));expect((await request(path,{model:"bad"})).status).toBe(400);expect(getSetting(key)).toBe("stamp");spy.mockImplementation(async id=>patchTask(id,{modelID:"applied"})!);vi.spyOn(marker,"clearGoalLoopAutoModel").mockImplementation(()=>{throw new Error("PRIVATE clear failure");});const id=randomUUID(),partial=await request(path,{model:"provider::applied"},"POST",id);expect(partial.status).toBe(500);expect(partial.body).toMatchObject({operation:{execution:"unknown"}});expect(JSON.stringify(partial.body)).not.toContain("PRIVATE");expect(getTask(task.id)?.modelID).toBe("applied");expect(getSetting(key)).toBe("stamp");expect((await request(path,{model:"provider::applied"},"POST",id)).status).toBe(409);});
 it("thinking and Agent selection/clear delegate once and persist owner summaries",async()=>{const task=goalTask();const thinking=vi.spyOn(harness,"setTaskThinkingLevel").mockImplementation(async(id,_level)=>patchTask(id,{thinkingLevel:"high"})!);const agent=vi.spyOn(harness,"setTaskAgent").mockImplementation(async(id,name)=>patchTask(id,{agent:name||null})!);expect((await request(`tasks/${task.id}/thinking`,{thinkingLevel:"high"})).body.task).toMatchObject({thinkingLevel:"high"});expect((await request(`tasks/${task.id}/agent`,{agent:"reviewer"})).body.task).toMatchObject({agent:"reviewer"});expect((await request(`tasks/${task.id}/agent`,{agent:""})).body.task).toMatchObject({agent:null});expect(thinking).toHaveBeenCalledWith(task.id,"high");expect(thinking).toHaveBeenCalledTimes(1);expect(agent).toHaveBeenCalledTimes(2);});
 it("real Goal marker uses the running loop identity and disabled can clear ended loops",async()=>{const task=goalTask(),path=`tasks/${task.id}/goal-loop-auto-model`,key=`goal-loop-auto-model:${task.id}`;expect((await request(path,{enabled:true},"PUT")).body.enabled).toBe(true);expect(getSetting(key)).toBe("stamp");writeFileSync(join(root,"goals-loop","settings-session.json"),JSON.stringify({sessionId:"settings-session",goal:"fixture",status:"completed",createdAt:"new-stamp"}));expect((await request(path,{enabled:true},"PUT")).status).toBe(409);expect(getSetting(key)).toBe("stamp");expect((await request(path,{enabled:false},"PUT")).body.enabled).toBe(false);expect(getSetting(key)).toBeNull();expect((await request("tasks/missing/goal-loop-auto-model",{enabled:false},"PUT")).status).toBe(404);});
 it("auth/Origin/bounds/body/IDs refuse before session/model calls",async()=>{const task=goalTask(),path=`tasks/${task.id}/model`,spy=vi.spyOn(harness,"setTaskModel"),files=readdirSync(root);expect((await request(path,{},"POST",randomUUID(),false)).status).toBe(401);expect((await request(path,{},"POST",randomUUID(),true,"https://evil.test")).status).toBe(403);expect((await request(path,"x".repeat(4097))).status).toBe(413);expect(readdirSync(root)).toEqual(files);for(const body of ["invalid",{}, {model:2},{model:" "}])expect((await request(path,body)).status).toBe(400);for(const id of ["..%2Fx","%252F"])expect((await request(`tasks/${id}/model`,{model:"p::m"})).status).toBe(400);expect((await request(`tasks/${task.id}/thinking`,{thinkingLevel:2})).status).toBe(400);expect((await request(`tasks/${task.id}/agent`,{agent:null})).status).toBe(400);expect(spy).not.toHaveBeenCalled();});
 it("Next cannot enter SDK model/thinking/Agent changes or write Auto markers or admission",async()=>{const task=goalTask(),files=readdirSync(root),before=getTask(task.id);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");await expect(owner.setTaskModel(task.id,"p::m")).rejects.toThrow("owned by Backend");for(const action of [()=>owner.setTaskThinkingLevel(task.id,"high"),()=>owner.setTaskAgent(task.id,""),()=>owner.setTaskGoalLoopAutoModel(task.id,true)])expect(action).toThrow("owned by Backend");await expect(request(`tasks/${task.id}/model`,{model:"p::m"})).rejects.toThrow("owned by Backend");expect(getTask(task.id)).toEqual(before);expect(readdirSync(root)).toEqual(files);});
});
