import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { dispatchJsonBusinessRequest } from "@backend-runtime/json-business/index";
import { publicJsonBusinessResult } from "@shared/json-business-contract.mjs";
import { insertTask, patchTask, getTask } from "@/lib/store";
import { taskBookmarks } from "@/lib/task-bookmarks";
import { readTaskTranscript, resetTaskTranscriptCache } from "@/lib/task-transcript";
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-task-history-"));vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",join(root,"agent"));resetTaskTranscriptCache();});
afterEach(()=>{vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
async function request(path:string,method="GET",query="",body?:unknown,id=method==="GET"?undefined:randomUUID(),authorized=true,origin?:string){
 const result=await dispatchJsonBusinessRequest({route:path,method,url:`http://localhost/api/${path}${query}`,headers:{host:"localhost",...(origin?{origin}:{})},authorized,operationId:id,...(body===undefined?{}:{body:new TextEncoder().encode(typeof body==="string"?body:JSON.stringify(body))})});
 const projected=publicJsonBusinessResult(path,result);expect(projected).not.toBeNull();return {...projected!,body:projected!.body!};
}
function transcript(){const task=insertTask({project:null,title:"History"}),file=join(root,`${task.id}.jsonl`);writeFileSync(file,[JSON.stringify({type:"session",version:3,id:randomUUID(),cwd:root,timestamp:new Date().toISOString()}),...Array.from({length:205},(_,i)=>JSON.stringify({type:"message",id:`u${i}`,parentId:i?`u${i-1}`:null,timestamp:new Date().toISOString(),message:{role:"user",content:[{type:"text",text:`履歴 line ${i}${i===0?" oldneedle":""}`},...(i===50?[{type:"image",mimeType:"image/png",data:"AAAA"}]:[])],timestamp:i}}))].join("\n")+"\n","utf8");patchTask(task.id,{status:"archived",sessionFile:file});return task;}
describe("Task history/search/bookmark Backend owner",()=>{
 it("pages a real 205-message transcript with stable cursors and omits old image bytes, never cold-hydrates",async()=>{const task=transcript();patchTask(task.id,{status:"idle"});const before=getTask(task.id),path=`tasks/${task.id}/messages`;const newest=await request(path);expect(newest.status).toBe(200);expect((newest.body.messages as unknown[]).length).toBeGreaterThan(0);expect(newest.body.messageHistory).toMatchObject({hasMore:true});const older=await request(path,"GET","?before=u100");expect(older.status).toBe(200);const messages=older.body.messages as {id:string;parts:{type:string;url?:string;filename?:string}[]}[];expect(messages.at(-1)?.id).toBe("u99");const image=messages.find(m=>m.id==="u50")?.parts.find(p=>p.type==="image");expect(image).toMatchObject({url:""});expect(image?.filename).toBeTruthy();expect((await request(path,"GET","?before=missing")).status).toBe(409);expect((await request(path,"GET","?before=%20")).status).toBe(400);expect(getTask(task.id)).toEqual(before);});
 it("searches beyond the newest page and returns UTF-16 snippet highlights and bounded newest hits",async()=>{const task=transcript(),path=`tasks/${task.id}/search`;const early=await request(path,"GET","?q=oldneedle");expect(early.status).toBe(200);expect(early.body.total).toBe(1);expect((early.body.hits as {messageId:string}[])[0].messageId).toBe("u0");const all=await request(path,"GET","?q=%E5%B1%A5%E6%AD%B4&limit=2");expect(all.body).toMatchObject({total:205,truncated:true});expect((all.body.hits as {messageId:string}[]).map(h=>h.messageId)).toEqual(["u203","u204"]);});
 it("stores, deduplicates, verifies missing messages and deletes through the shared durable Task ledger",async()=>{const task=transcript(),path=`tasks/${task.id}/bookmarks`,id=randomUUID();const add=await request(path,"PUT","",{messageId:"u0",role:"user",messageCreatedAt:0,preview:"private authored preview"},id);expect(add.body).toMatchObject({operation:{id,execution:"complete"}});expect((await request(path,"PUT","",{messageId:"u0",role:"user"},id)).status).toBe(409);await request(path,"PUT","",{messageId:"gone",role:"assistant",messageCreatedAt:300});await request(path,"PUT","",{messageId:"u0",role:"user"});const verified=await request(path,"GET","?verify=1");expect(verified.body.bookmarks).toHaveLength(2);expect(verified.body.missing).toEqual(["gone"]);expect(readFileSync(join(root,"task-collection-command.json"),"utf8")).not.toContain("private authored preview");expect((await request(path,"DELETE","?messageId=gone")).body.bookmarks).toHaveLength(1);});
 it("auth, Origin, malformed body, body ceiling, query and IDs refuse without writes",async()=>{const task=transcript(),path=`tasks/${task.id}/bookmarks`,before=readdirSync(root);expect((await request(path,"PUT","",{},undefined,false)).status).toBe(401);expect((await request(path,"PUT","",{},undefined,true,"https://evil.test")).status).toBe(403);expect(readdirSync(root)).toEqual(before);expect((await request(path,"PUT","","not-json")).status).toBe(400);expect((await request(path,"PUT","","x".repeat(16001))).status).toBe(413);expect((await request(`tasks/${task.id}/search`,"GET","?q="+"a".repeat(401))).status).toBe(400);for(const id of ["..%2Fx","%252F"]){expect((await request(`tasks/${id}/messages`)).status).toBe(400);}expect((await request("tasks/missing/messages")).status).toBe(404);});
 it("Next cannot read cached transcripts or create/backup/write bookmark files",async()=>{const task=transcript();await readTaskTranscript(task.id,{maxAgeMs:3000});taskBookmarks.add(task.id,{messageId:"u0",role:"user"});const file=join(root,"task-bookmarks.json"),before=readFileSync(file,"utf8"),files=readdirSync(root);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");await expect(readTaskTranscript(task.id,{maxAgeMs:3000})).rejects.toThrow("owned by Backend");for(const action of [()=>taskBookmarks.add(task.id,{messageId:"u1",role:"user"}),()=>taskBookmarks.remove(task.id,"u0")])expect(action).toThrow("owned by Backend");await expect(request(`tasks/${task.id}/bookmarks`,"PUT","",{})).rejects.toThrow("owned by Backend");expect(readFileSync(file,"utf8")).toBe(before);expect(readdirSync(root)).toEqual(files);});
});
