import{expect,it,vi,afterEach,beforeEach}from"vitest";import{mkdtempSync,rmSync}from"node:fs";import{join}from"node:path";import{tmpdir}from"node:os";let root:string;import{relayTaskFileStream}from"./task-file-stream-relay";const remote=vi.fn();beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"lcp-tts-relay-"));vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("PI_CODING_AGENT_DIR",root);for(const[k,v]of Object.entries({LEAFCODE_PI_PROCESS_ROLE:"next",LEAFCODE_PI_WEBUI_AUTH:"",LEAFCODE_PI_BACKEND_TOKEN:"fixture"+"x".repeat(32),LEAFCODE_PI_BACKEND_GENERATION:"",LEAFCODE_PI_BACKEND_GENERATION_FILE:""}))vi.stubEnv(k,v);remote.mockReset();vi.stubGlobal("fetch",remote);});afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
const request=(body="{}",headers:Record<string,string>={},signal=new AbortController().signal)=>new Request("http://localhost/api/tts/synthesize",{method:"POST",body,headers,signal});
it("restores the real Host authority after Next loopback normalization without widening Origin",async()=>{
 remote.mockImplementation(async(_url,options)=>new Response(new Uint8Array([1]),{headers:{"x-leafcode-backend-protocol":"1","x-leafcode-tts-operation":options.headers["x-leafcode-business-operation"],"x-leafcode-tts-execution":"unknown","content-type":"audio/wav"}}));
 const normalized=new Request("http://localhost:54321/api/tts/synthesize",{method:"POST",body:"{}",headers:{host:"127.0.0.1:54321",origin:"http://127.0.0.1:54321"}});
 const r=await relayTaskFileStream(normalized,"tts/synthesize");expect(r.status).toBe(200);await r.body!.cancel();expect(remote.mock.calls[0][1].headers["x-leafcode-business-origin"]).toBe("http://127.0.0.1:54321");
 const denied=new Request(normalized.url,{method:"POST",body:"{}",headers:{host:"127.0.0.1:54321",origin:"https://foreign.test"}});expect((await relayTaskFileStream(denied,"tts/synthesize")).status).toBe(403);expect(remote).toHaveBeenCalledOnce();
});
it("rejects malformed or multi-authority Host before admission",async()=>{
 for(const host of["user@localhost","localhost/path","localhost?query","localhost#hash","localhost,evil.test","localhost\\evil.test","localhost:bad"]){const req=new Request("http://localhost/api/tts/synthesize",{method:"POST",body:"{}",headers:{host}});expect((await relayTaskFileStream(req,"tts/synthesize")).status).toBe(400);}
 expect(remote).not.toHaveBeenCalled();
});
it("opaque JSON request and exact raw streamed chunks; ACK/protocol/type required",async()=>{remote.mockImplementationOnce(async(_url,options)=>{const id=new Headers(options.headers).get("x-leafcode-business-operation");return new Response(new Uint8Array([0,1,255]),{headers:{"x-leafcode-backend-protocol":"1","x-leafcode-tts-operation":id!,"x-leafcode-tts-execution":"unknown","content-type":"audio/wav","set-cookie":"PRIVATE"}});});const r=await relayTaskFileStream(request('{"text":"日本語","url":"ignored"}'),"tts/synthesize");expect(r.status).toBe(200);expect(r.headers.get("set-cookie")).toBeNull();expect([...new Uint8Array(await r.arrayBuffer())]).toEqual([0,1,255]);expect(new TextDecoder().decode(remote.mock.calls[0][1].body)).toBe('{"text":"日本語","url":"ignored"}');});
it("bounds/auth/Origin before owner and no automatic retry on missing ACK or disconnect",async()=>{expect((await relayTaskFileStream(request("x".repeat(16*1024+1)),"tts/synthesize")).status).toBe(413);expect((await relayTaskFileStream(request("{}",{origin:"https://evil.test"}),"tts/synthesize")).status).toBe(403);expect(remote).not.toHaveBeenCalled();remote.mockResolvedValueOnce(new Response(new Uint8Array([1]),{headers:{"x-leafcode-backend-protocol":"1","content-type":"audio/wav"}}));expect((await relayTaskFileStream(request(),"tts/synthesize")).status).toBe(503);expect(remote).toHaveBeenCalledOnce();remote.mockRejectedValueOnce(Error("PRIVATE"));const r=await relayTaskFileStream(request(),"tts/synthesize");expect((await r.json()).execution).toBe("unknown");});
