import test from"node:test";import assert from"node:assert/strict";import{mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync}from"node:fs";import{tmpdir}from"node:os";import{join,resolve}from"node:path";import{fork,spawnSync}from"node:child_process";import{createRequire}from"node:module";import{get}from"node:http";import{setTimeout as delay}from"node:timers/promises";import{createHash}from"node:crypto";
const require=createRequire(import.meta.url),{build}=require("esbuild"),ROOT=resolve("."),id="11111111-1111-4111-8111-111111111111",token="t".repeat(32);
test("real individual Task/Bot SSE:65sec,large events,cancels,stalled socket,reconnect,restart,readonly",{timeout:160000},async t=>{
 const dir=mkdtempSync(join(tmpdir(),"lcp-individual-events-")),data=join(dir,"data"),agent=join(dir,"agent"),session=join(dir,"s.jsonl"),children=[],samples={backend:[],relay:[]},streams=[];let backend,relay,base;mkdirSync(data);mkdirSync(agent);
 const save=text=>writeFileSync(session,JSON.stringify({type:"session",version:3,id:"s",cwd:dir})+"\n"+JSON.stringify({type:"message",id:"m",parentId:null,message:{role:"user",content:[{type:"text",text}],timestamp:1}})+"\n");save("persistent fixture");const digest=()=>createHash("sha256").update(readFileSync(session)).digest("hex"),before=digest(),stamp="2026-01-01T00:00:00.000Z";
 const task={id:"task",kind:"code",status:"idle",directory:dir,title:"fixture",sessionFile:session,sessionId:"s",createdAt:stamp,updatedAt:stamp};writeFileSync(join(data,"store.json"),JSON.stringify({version:1,projects:[],tasks:[task,{...task,id:"bot:"+id,kind:"bot",botId:id}]}));writeFileSync(join(data,"bots.json"),JSON.stringify({version:1,bots:[{id,name:"fixture",directory:dir,sessionFile:session,sessionId:"s",createdAt:stamp,updatedAt:stamp}]}));
 t.after(async()=>{await Promise.all(streams.map(close));for(const c of children.reverse())await stop(c);rmSync(dir,{recursive:true,force:true});});
 const env={...process.env,NODE_ENV:"test",LEAFCODE_PI_DATA_DIR:data,PI_CODING_AGENT_DIR:agent,APPDATA:join(dir,"appdata"),LEAFCODE_PI_DEFAULT_DIR:join(dir,"workspaces"),LEAFCODE_PI_BACKEND_TOKEN:token,LEAFCODE_PI_BACKEND_GENERATION:"",LEAFCODE_PI_BACKEND_GENERATION_FILE:"",LEAFCODE_PI_WEBUI_AUTH:"",LEAFCODE_PI_BACKEND_RUNTIME:""};
 const owner=join(ROOT,"backend/runtime/runtime.bundle.mjs"),client=join(dir,"relay.mjs");const built=spawnSync(process.execPath,[join(ROOT,"scripts/build-backend-runtime.mjs"),"--force"],{cwd:ROOT,encoding:"utf8",timeout:10000});assert.equal(built.status,0,built.stderr);
 await build({bundle:true,platform:"node",format:"esm",logLevel:"silent",banner:{js:'import{createRequire as __fixtureRequire}from"node:module";const require=__fixtureRequire('+JSON.stringify(join(ROOT,"backend/package.json"))+');'},entryPoints:[join(ROOT,"web/src/lib/live-event-relay.ts")],outfile:client,alias:{"@":join(ROOT,"web/src"),"@shared":join(ROOT,"shared"),"@backend-core":join(ROOT,"backend/core"),"@backend-runtime":join(ROOT,"backend/runtime-src")},tsconfig:join(ROOT,"web/tsconfig.json")});
 async function launch(role,extra={}){const child=fork(join(ROOT,"backend/src/individual-event-fixture.mjs"),[],{env:{...env,...extra,LEAFCODE_PI_PROCESS_ROLE:role==="backend"?"backend":"next",EVENT_FIXTURE_ROLE:role,EVENT_FIXTURE_BUNDLE:role==="backend"?owner:client},stdio:["ignore","ignore","pipe","ipc"]});children.push(child);let stderr="";child.stderr.on("data",b=>stderr+=b);return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(stderr||"fixture timeout")),10000);child.on("message",m=>{samples[role].push(m);if(m.type==="ready"){clearTimeout(timer);resolve({child,port:m.port});}});child.on("exit",code=>{clearTimeout(timer);if(code)reject(Error(stderr||"fixture died"));});});}
 async function stop(c){if(c.exitCode!==null||c.signalCode!==null)return;const exited=new Promise(r=>c.once("exit",r));c.disconnect?.();await Promise.race([exited,delay(1000)]);if(c.exitCode===null&&c.signalCode===null){c.kill();await exited;}}
 const latest=role=>samples[role].at(-1)?.state;async function settled(n=0){for(let i=0;i<160;i++){if(latest("backend")?.active===n&&latest("relay")?.active===n&&latest("backend").individualReads===0&&latest("backend").individualWaiters===0)return;await delay(25);}assert.fail(JSON.stringify({owner:latest("backend"),relay:latest("relay")}));}
 async function open(path="tasks/task/events",headers={}){const c=new AbortController(),r=await fetch(base+"/api/"+path,{signal:c.signal,headers});assert.equal(r.status,200);const reader=r.body.getReader(),s={c,reader,bytes:0,text:"",pings:0,error:null};streams.push(s);const decoder=new TextDecoder();s.done=(async()=>{try{for(;;){const part=await reader.read();if(part.done)break;s.bytes+=part.value.length;assert.ok(part.value.length<=65536);const text=decoder.decode(part.value,{stream:true});s.pings+=(text.match(/: ping/g)||[]).length;s.text=(s.text+text).slice(-100000);}}catch(e){s.error=e;}})();return s;}
 async function close(s){s.c.abort();await s.done;}async function text(s,value){for(let i=0;i<160;i++){if(s.text.includes(value))return;await delay(25);}assert.fail("missing "+value+"; actual "+s.text.slice(-1000));}
 backend=await launch("backend");relay=await launch("relay",{LEAFCODE_PI_BACKEND_URL:"http://127.0.0.1:"+backend.port});base="http://127.0.0.1:"+relay.port;
 assert.equal((await fetch("http://127.0.0.1:"+backend.port+"/internal/live-events/tasks/task/events")).status,401);assert.equal((await fetch(base+"/api/tasks/task/events",{method:"POST"})).status,405);assert.equal((await fetch(base+"/api/tasks/absent/events")).status,404);
 const first=await open();await text(first,'"eventType":"ready"');await text(first,"persistent fixture");await close(first);await settled();const bot=await open("bots/"+id+"/events");await text(bot,'"eventType":"ready"');await text(bot,'"intercomInbox"');await close(bot);await settled();assert.equal(digest(),before);
 for(let i=0;i<32;i++){const s=await open(i%2?"bots/"+id+"/events":"tasks/task/events");await text(s,'"eventType":"ready"');await close(s);}await settled();
 const one=await open(),two=await open("bots/"+id+"/events");await text(one,'"eventType":"ready"');await text(two,'"eventType":"ready"');await settled(2);const baseline={backend:samples.backend.at(-1).memory,relay:samples.relay.at(-1).memory},start={backend:samples.backend.length,relay:samples.relay.length};backend.child.send({type:"producer",interval:5,bytes:16384});const began=Date.now();await delay(65000);const elapsed=Date.now()-began;assert.ok(one.bytes>32*1024*1024);assert.ok(two.bytes>32*1024*1024);assert.ok(one.pings>=4&&two.pings>=4);assert.equal(one.error,null);assert.equal(two.error,null);await close(one);await close(two);await settled();const produced=latest("backend").emitted;await delay(100);assert.ok(latest("backend").emitted>produced);
 const slow=await new Promise((resolve,reject)=>{const req=get(base+"/api/tasks/task/events",res=>{res.pause();resolve({req,res});});req.on("error",reject);});await settled(1);backend.child.send({type:"producer",interval:1,bytes:65536});for(let i=0;i<500&&latest("backend").active;i++)await delay(100);assert.equal(latest("backend").active,0);slow.req.destroy();slow.res.destroy();await settled();backend.child.send({type:"producer",interval:0});assert.equal(digest(),before);
 const restored=await open(undefined,{"last-event-id":"stale-id"});await text(restored,"persistent fixture");await close(restored);await settled();const metrics={elapsed,bytes:one.bytes+two.bytes,disconnects:32,final:latest("backend"),relay:latest("relay").active,peaks:{}};for(const role of["backend","relay"]){const d=Object.fromEntries(["rss","heapUsed","external"].map(k=>[k,Math.max(...samples[role].slice(start[role]).map(s=>s.memory[k]))-baseline[role][k]]));metrics.peaks[role]=d;assert.ok(d.rss<128*1024*1024,role+" RSS "+JSON.stringify(d));assert.ok(d.heapUsed<48*1024*1024,role+" heap "+JSON.stringify(d));assert.ok(d.external<96*1024*1024,role+" buffers "+JSON.stringify(d));}t.diagnostic(JSON.stringify(metrics));for(const key of["active","individualSubscriptions","individualReads","individualWaiters","individualPendingBytes","individualPollTimers","writers","queuedBytes","heartbeats","stallTimers","taskListeners","botListeners"])assert.equal(latest("backend")[key],0,key);
 await stop(relay.child);await stop(backend.child);backend=await launch("backend");relay=await launch("relay",{LEAFCODE_PI_BACKEND_URL:"http://127.0.0.1:"+backend.port});base="http://127.0.0.1:"+relay.port;const restart=await open();await text(restart,"persistent fixture");await close(restart);await settled();const botRestart=await open("bots/"+id+"/events");await text(botRestart,'"eventType":"ready"');await close(botRestart);await settled();assert.equal(digest(),before);
});
