import test from"node:test";import assert from"node:assert/strict";import{mkdtempSync,mkdirSync,writeFileSync,rmSync}from"node:fs";import{tmpdir}from"node:os";import{join,resolve}from"node:path";import{fork,spawnSync}from"node:child_process";import{createRequire}from"node:module";import{get}from"node:http";import{setTimeout as delay}from"node:timers/promises";
const require=createRequire(import.meta.url),{build}=require("esbuild"),root=resolve("."),id="11111111-1111-4111-8111-111111111111",token="t".repeat(32);
test("isolated real two-hop Room/Bot SSE:65sec,byte bounds,disconnect,reconnect,stalled consumer and restart",{timeout:150000},async(t)=>{
 const dir=mkdtempSync(join(tmpdir(),"lcp-live-events-")),children=[],samples={backend:[],relay:[]};let backend,relay,base,privateBase;const streams=[];
 t.after(async()=>{for(const c of children.reverse())await stop(c);rmSync(dir,{recursive:true,force:true});});
 const room={id,name:"fixture",members:[],createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",messages:[]};
 const roomPath=join(dir,"data","bots","rooms",id+".json");mkdirSync(join(dir,"data","bots","rooms"),{recursive:true});writeFileSync(roomPath,JSON.stringify(room));
 const env={...process.env,LEAFCODE_PI_DATA_DIR:join(dir,"data"),LEAFCODE_PI_AGENT_DIR:join(dir,"agent"),PI_CODING_AGENT_DIR:join(dir,"agent"),APPDATA:join(dir,"appdata"),LEAFCODE_PI_BACKEND_TOKEN:token,LEAFCODE_PI_BACKEND_GENERATION:"",LEAFCODE_PI_BACKEND_GENERATION_FILE:"",LEAFCODE_PI_WEBUI_AUTH:"",LEAFCODE_PI_BACKEND_RUNTIME:"",EVENT_FIXTURE_ROOM:roomPath};
 const buildBase={bundle:true,platform:"node",format:"esm",logLevel:"silent",banner:{js:'import{createRequire as __fixtureRequire}from"node:module";const require=__fixtureRequire('+JSON.stringify(join(root,"backend","package.json"))+');'},alias:{"@shared":join(root,"shared"),"@backend-core":join(root,"backend","core")}};
 const owner=join(root,"backend/runtime/runtime.bundle.mjs"),client=join(dir,"relay.mjs");
 const built=spawnSync(process.execPath,[join(root,"scripts/build-backend-runtime.mjs"),"--force"],{cwd:root,encoding:"utf8",timeout:10000});assert.equal(built.status,0,built.stderr);
 await build({...buildBase,entryPoints:[join(root,"web/src/lib/live-event-relay.ts")],outfile:client,alias:{...buildBase.alias,"@":join(root,"web/src")},tsconfig:join(root,"web/tsconfig.json")});
 async function spawn(role,extra={}){const child=fork(join(root,"backend/src/live-event-fixture.mjs"),[],{env:{...env,...extra,LEAFCODE_PI_PROCESS_ROLE:role==="backend"?"backend":"next",EVENT_FIXTURE_ROLE:role,EVENT_FIXTURE_BUNDLE:role==="backend"?owner:client},stdio:["ignore","ignore","pipe","ipc"]});children.push(child);let stderr="";child.stderr.on("data",b=>stderr+=b);return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(stderr||"fixture timeout")),10000);child.on("message",m=>{samples[role].push(m);if(m.type==="ready"){clearTimeout(timer);resolve({child,port:m.port});}});child.on("exit",code=>{clearTimeout(timer);if(code)reject(new Error(stderr||"fixture exited"));});});}
 async function stop(child){if(child.exitCode!==null||child.signalCode!==null)return;child.disconnect?.();await Promise.race([new Promise(r=>child.once("exit",r)),delay(1000)]);if(child.exitCode===null&&child.signalCode===null){child.kill();await new Promise(r=>child.once("exit",r));}}
 const latest=role=>samples[role].at(-1)?.state;
 async function settled(expected=0){for(let i=0;i<100;i++){if(latest("backend")?.active===expected&&latest("relay")?.active===expected&&latest("backend")?.pendingReads===0)return;await delay(25);}assert.fail(JSON.stringify({backend:latest("backend"),relay:latest("relay")}));}
 async function open(path="bots/events"){const c=new AbortController(),response=await fetch(base+"/api/"+path,{signal:c.signal});assert.equal(response.status,200);const reader=response.body.getReader(),item={c,reader,bytes:0,text:"",pings:0,error:null};streams.push(item);item.done=(async()=>{try{while(true){const x=await reader.read();if(x.done)break;item.bytes+=x.value.length;assert.ok(x.value.length<=65536);const text=new TextDecoder().decode(x.value);item.pings+=(text.match(/: ping/g)||[]).length;item.text=(item.text+text).slice(-100000);}}catch(e){item.error=e;}})();return item;}
 async function close(item){item.c.abort();await item.done;}
 async function waitText(item,text){for(let i=0;i<100;i++){if(item.text.includes(text))return;await delay(25);}assert.fail("missing SSE text "+text);}
 try{
  backend=await spawn("backend");privateBase="http://127.0.0.1:"+backend.port;relay=await spawn("relay",{LEAFCODE_PI_BACKEND_URL:privateBase});base="http://127.0.0.1:"+relay.port;
  const forbidden=await fetch(privateBase+"/internal/live-events/bots/events");assert.equal(forbidden.status,401);await forbidden.body.cancel();
  const publicMethod=await fetch(base+"/api/bots/events",{method:"POST"});assert.equal(publicMethod.status,405);await publicMethod.body.cancel();
  const invalid=await fetch(base+"/api/bots/rooms/%00/events");assert.equal(invalid.status,404);await invalid.body.cancel();
  const missing=await fetch(base+"/api/bots/rooms/22222222-2222-4222-8222-222222222222/events");assert.equal(missing.status,404);await missing.body.cancel();
  const bootstrap=await open("bots/rooms/"+id+"/events");await waitText(bootstrap,'"room"');room.name="reconnected";room.updatedAt="2026-01-01T00:00:01.000Z";backend.child.send({type:"room",room});await waitText(bootstrap,"reconnected");await close(bootstrap);await settled();
  const again=await open("bots/rooms/"+id+"/events");await waitText(again,"reconnected");await close(again);await settled();
  for(let i=0;i<32;i++){const s=await open();await waitText(s,": connected");await close(s);}await settled();
  const one=await open(),two=await open("bots/rooms/"+id+"/events");await waitText(two,"reconnected");await settled(2);
  const baseline={backend:samples.backend.at(-1).memory,relay:samples.relay.at(-1).memory};const start={backend:samples.backend.length,relay:samples.relay.length};
  backend.child.send({type:"producer",interval:5,bytes:16384});const started=Date.now();await delay(65000);const elapsed=Date.now()-started;assert.ok(one.bytes>=32*1024*1024);assert.ok(one.text.includes("event: routine"));assert.ok(two.pings>=4);assert.equal(one.error,null);assert.equal(two.error,null);await close(one);await close(two);await settled();
  const emitted=latest("backend").emitted;await delay(100);assert.ok(latest("backend").emitted>emitted,"consumer cancellation must not stop producer");
  // An unread socket forces transport drain deadline or bounded queue overflow, not agent cancellation.
  const slow=await new Promise((resolve,reject)=>{const req=get(base+"/api/bots/events",res=>{res.pause();resolve({req,res});});req.on("error",reject);});await settled(1);backend.child.send({type:"producer",interval:1,bytes:65536});
  for(let i=0;i<500&&latest("backend").active;i++)await delay(100);assert.equal(latest("backend").active,0,"slow consumer must release owner");slow.req.destroy();slow.res.destroy();await settled();backend.child.send({type:"producer",interval:0});
  const restore=await open("bots/rooms/"+id+"/events");await waitText(restore,"reconnected");await close(restore);await settled();
  for(const role of["backend","relay"]){const max={};for(const key of["rss","heapUsed","external"])max[key]=Math.max(...samples[role].slice(start[role]).map(s=>s.memory[key]))-baseline[role][key];assert.ok(max.rss<128*1024*1024,role+" RSS "+max.rss);assert.ok(max.heapUsed<48*1024*1024,role+" heap "+max.heapUsed);assert.ok(max.external<96*1024*1024,role+" external "+max.external);console.log(JSON.stringify({role,elapsed,bytes:one.bytes,peakDeltas:max,final:latest(role)}));}
  assert.deepEqual(Object.fromEntries(["active","subscriptions","pollTimers","pendingReads","retainedSnapshotBytes","writers","queuedBytes","heartbeats","stallTimers","metadataActive","metadataQueued","routineListeners"].map(key=>[key,latest("backend")[key]])),Object.fromEntries(["active","subscriptions","pollTimers","pendingReads","retainedSnapshotBytes","writers","queuedBytes","heartbeats","stallTimers","metadataActive","metadataQueued","routineListeners"].map(key=>[key,0])));
  assert.ok(latest("backend").peakQueuedBytes<=16*1024*1024);
  await stop(relay.child);await stop(backend.child);backend=await spawn("backend");privateBase="http://127.0.0.1:"+backend.port;relay=await spawn("relay",{LEAFCODE_PI_BACKEND_URL:privateBase});base="http://127.0.0.1:"+relay.port;const restarted=await open("bots/rooms/"+id+"/events");await waitText(restarted,"reconnected");await close(restarted);await settled();console.log("restart: full Room snapshot restored, no inference or public network");
 }finally{await Promise.all(streams.map(close));for(const c of children.reverse())await stop(c);rmSync(dir,{recursive:true,force:true});}
});
