import assert from "node:assert/strict";import test from "node:test";import {fork,spawnSync}from"node:child_process";import{createRequire}from"node:module";import{mkdtempSync,mkdirSync,writeFileSync,appendFileSync,readFileSync,rmSync}from"node:fs";import{join}from"node:path";import{tmpdir}from"node:os";import{fileURLToPath}from"node:url";import{setTimeout as delay}from"node:timers/promises";import{randomBytes,createHash}from"node:crypto";import{gunzipSync}from"node:zlib";
const ROOT=fileURLToPath(new URL("../../",import.meta.url)),require=createRequire(new URL("../package.json",import.meta.url)),esbuild=require("esbuild");
test("profile v1:512MiB source,64MiB resource,2-hop cancellation/restart/memory",{timeout:110000},async t=>{
 const root=mkdtempSync(join(tmpdir(),"lcp-profile-export-")),data=join(root,"data"),agent=join(root,"agent"),children=[],samples={backend:[],next:[]},last={};mkdirSync(data);mkdirSync(agent);mkdirSync(join(agent,"skills"));const path=join(agent,"skills","resource.bin"),chunk=randomBytes(8*1024*1024);writeFileSync(path,chunk);for(let i=1;i<8;i++)appendFileSync(path,chunk);writeFileSync(join(agent,"AGENTS.md"),"fixture-日本語");writeFileSync(join(agent,"auth.json"),"not-exported");
 t.after(async()=>{for(const child of children)if(child.exitCode===null&&child.signalCode===null){const exit=new Promise(r=>child.once("exit",r));child.kill();await exit;}rmSync(root,{recursive:true,force:true});});
 const digest=()=>createHash("sha256").update(readFileSync(path)).digest("hex"),before=digest();const build=spawnSync(process.execPath,[join(ROOT,"scripts/build-backend-runtime.mjs"),"--force"],{cwd:ROOT,encoding:"utf8",timeout:10000});assert.equal(build.status,0,build.stderr);
 const relay=join(root,"relay.mjs");await esbuild.build({entryPoints:[join(ROOT,"web/src/lib/task-file-stream-relay.ts")],outfile:relay,bundle:true,platform:"node",format:"esm",packages:"external",alias:{"@":join(ROOT,"web/src"),"@shared":join(ROOT,"shared"),"@backend-core":join(ROOT,"backend/core"),"@backend-runtime":join(ROOT,"backend/runtime-src")},logLevel:"silent"});const token="fixture"+"x".repeat(32);
 async function launch(role,bundle,backendUrl=""){const child=fork(join(ROOT,"backend/src/task-file-stream-fixture.mjs"),[],{stdio:["ignore","ignore","pipe","ipc"],env:{...process.env,NODE_ENV:"test",APPDATA:join(root,"roaming"),PI_CODING_AGENT_DIR:agent,LEAFCODE_PI_DATA_DIR:data,LEAFCODE_PI_DEFAULT_DIR:join(root,"workspaces"),LEAFCODE_PI_PROCESS_ROLE:role,LEAFCODE_PI_BACKEND_GENERATION:"",LEAFCODE_PI_BACKEND_GENERATION_FILE:"",LEAFCODE_PI_BACKEND_URL:backendUrl,LEAFCODE_PI_BACKEND_TOKEN:token,LEAFCODE_PI_WEBUI_AUTH:"required",LEAFCODE_PI_WEBUI_TOKEN:token,FILE_FIXTURE_ROLE:role,FILE_FIXTURE_BUNDLE:bundle}});children.push(child);let errors="";child.stderr.on("data",b=>errors+=b);return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(errors||"fixture timeout")),10000);child.on("message",m=>{last[role]=m;samples[role].push(m);if(m.type==="ready"){clearTimeout(timer);resolve({base:"http://127.0.0.1:"+m.port,child});}});child.on("exit",code=>{clearTimeout(timer);if(code)reject(Error(errors||"fixture died"));});});}
 let backend=await launch("backend",join(ROOT,"backend/runtime/runtime.bundle.mjs")),next=await launch("next",relay,backend.base);const get=(query="",options={})=>fetch(next.base+"/api/profile"+query,{...options,headers:{authorization:"Bearer "+token,...options.headers}});
 async function settle(){for(let i=0;i<160;i++){for(const child of children)if(child.connected)child.send("sample");await delay(25);const s=last.backend?.state;if(s?.active===0&&s.profileActive===0&&s.profileDescriptors===0&&s.profileDirectories===0&&s.profileCompressors===0&&s.profileMetadataBytes===0&&last.next?.state.active===0)return;}assert.fail(JSON.stringify(last));}
 assert.equal((await fetch(next.base+"/api/profile")).status,401);assert.equal((await get("",{headers:{origin:"https://foreign.test"}})).status,403);
 const head=await get("",{method:"HEAD"});assert.equal(head.status,200);assert.equal(head.headers.get("accept-ranges"),"none");assert.equal((await head.arrayBuffer()).byteLength,0);assert.ok(head.headers.get("content-disposition").endsWith('.lcp.gz"'));
 const range=await get("",{headers:{range:"bytes=0-3"}});assert.equal(range.status,200);assert.equal(range.headers.get("content-range"),null);await range.body.cancel();await settle();const baseline={backend:last.backend.memory,next:last.next.memory};samples.backend=[];samples.next=[];let transferred=0;
 for(let round=0;round<4;round++)await Promise.all(Array.from({length:2},async()=>{const r=await get();assert.equal(r.status,200);assert.equal(r.headers.get("content-type"),"application/gzip");const reader=r.body.getReader();for(;;){const p=await reader.read();if(p.done)break;transferred+=p.value.length;}reader.releaseLock();}));
 assert.ok(transferred>512*1024*1024);await settle();const sourceBytes=last.backend.state.profileBytesRead;
 for(let i=0;i<32;i++){const r=await get(),reader=r.body.getReader();await reader.read();await reader.cancel();}await settle();assert.ok(last.backend.state.profileBytesRead-sourceBytes<32*2*1024*1024,"disconnect must not drain source");
 const aborted=Array.from({length:16},()=>new AbortController()),pending=aborted.map(c=>get("",{signal:c.signal}));setTimeout(()=>aborted.forEach(c=>c.abort()),10);await Promise.allSettled(pending);await settle();assert.equal(digest(),before);
 const metrics={sourceBytes:512*1024*1024,transferred,disconnects:32,inventoryCancellations:16,final:last.backend.state,relay:last.next.state.active,peaks:{}};for(const role of["backend","next"]){const delta=Object.fromEntries(["rss","heapUsed","external"].map(key=>[key,Math.max(...samples[role].map(s=>s.memory[key]))-baseline[role][key]]));metrics.peaks[role]=delta;assert.ok(delta.rss<128*1024*1024,role+" RSS "+JSON.stringify(delta));assert.ok(delta.heapUsed<48*1024*1024,role+" heap "+JSON.stringify(delta));assert.ok(delta.external<96*1024*1024,role+" buffers "+JSON.stringify(delta));}t.diagnostic(JSON.stringify(metrics));
 for(const child of[next.child,backend.child]){const exit=new Promise(r=>child.once("exit",r));child.kill();await exit;}writeFileSync(path,Buffer.from([0,1,2,3,254,255]));backend=await launch("backend",join(ROOT,"backend/runtime/runtime.bundle.mjs"));next=await launch("next",relay,backend.base);const restored=await get(),archive=JSON.parse(gunzipSync(Buffer.from(await restored.arrayBuffer())).toString());assert.equal(archive.format,"leafcode-pi-profile");assert.equal(archive.version,1);assert.deepEqual(Buffer.from(archive.files["agent/skills/resource.bin"],"base64"),Buffer.from([0,1,2,3,254,255]));assert.equal(Buffer.from(archive.files["agent/AGENTS.md"],"base64").toString(),"fixture-日本語");assert.equal(archive.files["agent/auth.json"],undefined);assert.equal(typeof archive.modes["agent/skills/resource.bin"],"number");assert.deepEqual((await(await get("?backups")).json()).backups,[]);await settle();
});
