import assert from"node:assert/strict";import test from"node:test";import{fork,spawnSync}from"node:child_process";import{createRequire}from"node:module";import{createServer}from"node:http";import{mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync}from"node:fs";import{join}from"node:path";import{tmpdir}from"node:os";import{fileURLToPath}from"node:url";import{setTimeout as delay}from"node:timers/promises";
const ROOT=fileURLToPath(new URL("../../",import.meta.url)),require=createRequire(new URL("../package.json",import.meta.url)),esbuild=require("esbuild");
test("real TTS owner/relay/engine:512MiB clips,cancelled reads,shielded attempt,no-replay restart,memory",{timeout:110000},async t=>{
 const root=mkdtempSync(join(tmpdir(),"lcp-tts-audio-")),data=join(root,"data"),agent=join(root,"agent"),children=[],samples={backend:[],next:[]},last={};mkdirSync(data);mkdirSync(agent);let engineCalls=0,engineActive=0,engineCancelled=0;const size=64*1024*1024,chunk=Buffer.alloc(65536,0x81);
 const engine=createServer(async(req,res)=>{engineCalls++;engineActive++;let closed=false,complete=false;const close=()=>{if(!closed){closed=true;engineActive--;if(!complete)engineCancelled++;}};res.once("close",close);try{const parts=[];for await(const b of req)parts.push(b);const body=JSON.parse(Buffer.concat(parts));assert.equal(body.language,"Japanese");assert.equal(body.voice,"fixture-voice");if(body.text==="hold")await delay(200);if(res.destroyed)return;res.writeHead(200,{"content-type":"audio/wav","content-length":body.text==="small"?4:size,"set-cookie":"PRIVATE"});if(body.text==="small"){complete=true;res.end(Buffer.from([0,1,2,255]));return;}for(let at=0;at<size&&!res.destroyed;at+=chunk.length){if(!res.write(chunk))await new Promise(r=>{const done=()=>{res.off("drain",done);res.off("close",done);r();};res.once("drain",done);res.once("close",done);});}if(!res.destroyed){complete=true;res.end();}}finally{if(res.writableFinished)close();}});
 await new Promise(r=>engine.listen(0,"127.0.0.1",r));writeFileSync(join(data,"tts.json"),JSON.stringify({enabled:true,url:"http://127.0.0.1:"+engine.address().port+"/v1/tts",voice:"fixture-voice"}));
 t.after(async()=>{for(const child of children)if(child.exitCode===null&&child.signalCode===null){const exit=new Promise(r=>child.once("exit",r));child.kill();await exit;}engine.closeAllConnections();await new Promise(r=>engine.close(r));rmSync(root,{recursive:true,force:true});});
 const built=spawnSync(process.execPath,[join(ROOT,"scripts/build-backend-runtime.mjs"),"--force"],{cwd:ROOT,encoding:"utf8",timeout:10000});assert.equal(built.status,0,built.stderr);const relay=join(root,"relay.mjs");await esbuild.build({entryPoints:[join(ROOT,"web/src/lib/task-file-stream-relay.ts")],outfile:relay,bundle:true,platform:"node",format:"esm",packages:"external",alias:{"@":join(ROOT,"web/src"),"@shared":join(ROOT,"shared"),"@backend-core":join(ROOT,"backend/core"),"@backend-runtime":join(ROOT,"backend/runtime-src")},logLevel:"silent"});
 const token="fixture"+"x".repeat(32);
 async function launch(role,bundle,backendUrl=""){const child=fork(join(ROOT,"backend/src/task-file-stream-fixture.mjs"),[],{stdio:["ignore","ignore","pipe","ipc"],env:{...process.env,NODE_ENV:"test",APPDATA:join(root,"roaming"),PI_CODING_AGENT_DIR:agent,LEAFCODE_PI_DATA_DIR:data,LEAFCODE_PI_DEFAULT_DIR:join(root,"workspaces"),LEAFCODE_PI_PROCESS_ROLE:role,LEAFCODE_PI_BACKEND_GENERATION:"",LEAFCODE_PI_BACKEND_GENERATION_FILE:"",LEAFCODE_PI_BACKEND_URL:backendUrl,LEAFCODE_PI_BACKEND_TOKEN:token,LEAFCODE_PI_WEBUI_AUTH:"required",LEAFCODE_PI_WEBUI_TOKEN:token,FILE_FIXTURE_ROLE:role,FILE_FIXTURE_BUNDLE:bundle}});children.push(child);let errors="";child.stderr.on("data",b=>errors+=b);return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(errors||"fixture timeout")),10000);child.on("message",m=>{last[role]=m;samples[role].push(m);if(m.type==="ready"){clearTimeout(timer);resolve({base:"http://127.0.0.1:"+m.port,child});}});child.on("exit",code=>{clearTimeout(timer);if(code)reject(Error(errors||"fixture died"));});});}
 let backend=await launch("backend",join(ROOT,"backend/runtime/runtime.bundle.mjs")),next=await launch("next",relay,backend.base);
 const get=(text="clip",options={})=>fetch(next.base+"/api/tts/synthesize",{method:"POST",...options,headers:{authorization:"Bearer "+token,"content-type":"application/json",...options.headers},body:JSON.stringify({text})});
 const replay=id=>fetch(backend.base+"/internal/file-stream/tts/synthesize",{method:"POST",headers:{authorization:"Bearer "+token,"x-leafcode-backend-protocol":"1","x-leafcode-business-origin":"http://localhost","x-leafcode-business-host":"localhost","x-leafcode-business-authorized":"1","x-leafcode-business-operation":id},body:'{"text":"FORGED"}'});
 async function settle(){for(let i=0;i<160;i++){for(const c of children)if(c.connected)c.send("sample");await delay(25);const s=last.backend?.state;if(s?.active===0&&s.ttsActive===0&&s.ttsReaders===0&&s.ttsHeldChunkBytes===0&&last.next?.state.active===0&&engineActive===0)return;}assert.fail(JSON.stringify({last,engineActive}));}
 const warm=await get("small",{headers:{range:"bytes=0-0","if-range":"ignored"}});assert.equal(warm.status,200);assert.deepEqual([...new Uint8Array(await warm.arrayBuffer())],[0,1,2,255]);assert.equal(warm.headers.get("content-length"),null);assert.equal(warm.headers.get("accept-ranges"),"none");assert.equal(warm.headers.get("set-cookie"),null);const completeId=warm.headers.get("x-leafcode-tts-operation");assert.equal((await replay(completeId)).status,409);await settle();samples.backend=[];samples.next=[];const baseline={backend:last.backend.memory,next:last.next.memory};let total=0;
 for(let i=0;i<4;i++)await Promise.all(Array.from({length:2},async()=>{const r=await get();assert.equal(r.status,200);const reader=r.body.getReader();for(;;){const p=await reader.read();if(p.done)break;total+=p.value.length;assert.equal(p.value[0],0x81);}reader.releaseLock();}));assert.equal(total,512*1024*1024);
 let cancelledId;for(let i=0;i<32;i++){const r=await get();assert.equal(r.status,200);cancelledId=r.headers.get("x-leafcode-tts-operation");const reader=r.body.getReader();await reader.read();await reader.cancel();await settle();}assert.equal((await replay(cancelledId)).status,409);
 const c=new AbortController(),before=engineCalls,pending=get("hold",{signal:c.signal});for(let i=0;i<100&&engineCalls===before;i++)await delay(5);assert.equal(engineCalls,before+1);c.abort();await pending.catch(()=>{});await settle();
 const ledger=JSON.parse(readFileSync(join(data,"tts-synthesis-command.json"),"utf8"));assert.equal(ledger.operations.find(r=>r.id===completeId).execution,"complete");assert.equal(ledger.operations.find(r=>r.id===cancelledId).execution,"unknown");for(const secret of["fixture-voice","FORGED","127.0.0.1"])assert.ok(!JSON.stringify(ledger).includes(secret));
 const metrics={bytes:total,disconnects:32,headerWaitAbort:1,engineCalls,engineCancelled,final:last.backend.state,relay:last.next.state.active,engineActive,peaks:{}};for(const role of["backend","next"]){const delta=Object.fromEntries(["rss","heapUsed","external"].map(key=>[key,Math.max(...samples[role].map(s=>s.memory[key]))-baseline[role][key]]));metrics.peaks[role]=delta;assert.ok(delta.rss<128*1024*1024,role+" RSS "+JSON.stringify(delta));assert.ok(delta.heapUsed<48*1024*1024,role+" heap "+JSON.stringify(delta));assert.ok(delta.external<96*1024*1024,role+" buffers "+JSON.stringify(delta));}t.diagnostic(JSON.stringify(metrics));
 for(const child of[next.child,backend.child]){const exit=new Promise(r=>child.once("exit",r));child.kill();await exit;}backend=await launch("backend",join(ROOT,"backend/runtime/runtime.bundle.mjs"));next=await launch("next",relay,backend.base);const beforeRestart=engineCalls;assert.equal((await replay(completeId)).status,409);assert.equal((await replay(cancelledId)).status,409);assert.equal(engineCalls,beforeRestart);const after=await get("small");assert.deepEqual([...new Uint8Array(await after.arrayBuffer())],[0,1,2,255]);await settle();
});
