import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
const state=vi.hoisted(()=>({stop:vi.fn(async()=>0),cancel:vi.fn(async()=>0),clear:vi.fn()}));
vi.mock("@/lib/pi/harness",()=>({clearPendingAttentionForTask:state.clear,jsonError:(error:Error&{status?:number})=>({error:error.message,status:error.status??500})}));
vi.mock("@/lib/room-runtime",()=>({stopRoomTurns:state.stop}));
vi.mock("@/lib/pi/bot-code-relay",()=>({cancelRoomCodeRequests:state.cancel}));
import { createBot } from "@/lib/bots";
import { appendRoomMessage,createRoom,getRoom,roomBotTaskId,saveRoomFiles,updateRoomMessage } from "@/lib/rooms";
import { POST } from "@backend-runtime/json-business/handlers/bots/rooms/[id]/revert/route";
let root:string;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),"leafcode-room-revert-"));vi.stubEnv("LEAFCODE_PI_DATA_DIR",root);vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","backend");vi.clearAllMocks();});
afterEach(()=>{vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
const send=(id:string,body:unknown)=>POST(new Request("http://localhost",{method:"POST",body:JSON.stringify(body)}),{params:Promise.resolve({id})});
describe("Room rewind owner",()=>{
 it("stops then rewinds shared history, clears member attention, cancels every discarded request and restores authored files",async()=>{const bot=createBot({}),room=createRoom({members:[bot.id]}),a=appendRoomMessage(room.id,{role:"user",text:"Keep"})!,b=appendRoomMessage(room.id,{role:"user",text:"Edit 日本語"})!,c=appendRoomMessage(room.id,{role:"user",text:"Later"})!;const data=Buffer.from("Authored 日本語").toString("base64"),files=saveRoomFiles(room.id,b.id,[{name:"authored 日本語.txt",mimeType:"text/plain",data}]);updateRoomMessage(room.id,b.id,{files});const response=await send(room.id,{messageId:b.id});expect(response.status).toBe(200);expect(await response.json()).toMatchObject({room:{messages:[{id:a.id}]},text:"Edit 日本語",files:[{uri:"data:text/plain;base64,"+data,name:"authored 日本語.txt"}]});expect(state.stop).toHaveBeenCalledExactlyOnceWith(room.id);expect(state.clear).toHaveBeenCalledExactlyOnceWith(roomBotTaskId(room.id,bot.id));expect(state.cancel).toHaveBeenCalledWith(room.id,b.id);expect(state.cancel).toHaveBeenCalledWith(room.id,c.id);});
 it("missing/assistant/oversized/controlled targets refuse before stopping",async()=>{const room=createRoom({}),reply=appendRoomMessage(room.id,{role:"assistant",text:"No"})!;for(const [body,status]of [[{},400],[{messageId:reply.id},404],[{messageId:"missing"},404],[{messageId:"x".repeat(257)},400],[{messageId:"bad\u0000"},400]]as const)expect((await send(room.id,body)).status).toBe(status);expect(state.stop).not.toHaveBeenCalled();expect(getRoom(room.id)?.messages).toHaveLength(1);});
 it("typed post-rewind cancel failure remains unknown with actual truncated history, not a false refusal/rollback",async()=>{const room=createRoom({}),target=appendRoomMessage(room.id,{role:"user",text:"Edit"})!;state.cancel.mockRejectedValueOnce(Object.assign(new Error("PRIVATE/path"),{status:409}));const response=await send(room.id,{messageId:target.id});expect(response.status).toBe(503);expect(JSON.stringify(await response.json())).not.toContain("PRIVATE");expect(getRoom(room.id)?.messages).toEqual([]);});
 it("Next refuses before storage or room stop",async()=>{const room=createRoom({});vi.stubEnv("LEAFCODE_PI_PROCESS_ROLE","next");await expect(send(room.id,{messageId:"target"})).rejects.toThrow("owned by Backend");expect(state.stop).not.toHaveBeenCalled();});
});
