"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { getJson, sendJson } from "@/lib/client";
import type { BotDto, PermissionRequestDto, UiMessage } from "@/lib/types";
import { Button } from "@/components/ui";

function textOf(message: UiMessage): string { return message.parts.filter((p) => p.type === "text").map((p) => p.text).join(""); }
export function BotView({ id }: { id: string }) {
  const [bot, setBot] = useState<BotDto | null>(null); const [permission, setPermission] = useState<PermissionRequestDto | null>(null); const [messages, setMessages] = useState<UiMessage[]>([]); const [prompt, setPrompt] = useState(""); const [soul, setSoul] = useState(""); const [sending, setSending] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => getJson<{ bot: BotDto }>(`/api/bots/${encodeURIComponent(id)}`).then((r) => { setBot(r.bot); setSoul(r.bot.soul); }).catch((e) => setError(e instanceof Error ? e.message : "Load failed")), [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    let closed = false; let source: EventSource | null = null; let retry: ReturnType<typeof setTimeout> | null = null;
    const connect = () => { if (closed) return; source?.close(); source = new EventSource(`/api/bots/${encodeURIComponent(id)}/events?epoch=${Date.now()}`);
      source.addEventListener("snapshot", (event) => { try { const p = JSON.parse((event as MessageEvent).data) as { messages?: UiMessage[]; isStreaming?: boolean; error?: string; permissionRequest?: PermissionRequestDto | null }; if (p.messages) setMessages(p.messages); setPermission(p.permissionRequest ?? null); setSending(Boolean(p.isStreaming)); if (p.error) setError(p.error); } catch { setError("Could not parse event"); } });
      source.onerror = () => { source?.close(); if (!closed) { retry = setTimeout(connect, 1500); } };
    }; connect(); return () => { closed = true; if (retry) clearTimeout(retry); source?.close(); };
  }, [id]);
  const send = async () => { const value = prompt.trim(); if (!value || sending) return; setPrompt(""); setError(null); setSending(true); try { await sendJson(`/api/bots/${encodeURIComponent(id)}/prompt`, { prompt: value }); } catch (e) { setSending(false); setError(e instanceof Error ? e.message : "Request failed"); } };
  const respond = async (approved: boolean) => { if (!permission) return; try { await sendJson(`/api/tasks/${encodeURIComponent(`bot:${id}`)}/permission`, { requestId: permission.id, approved }); setPermission(null); } catch (e) { setError(e instanceof Error ? e.message : "Permission request failed"); } };
  const abort = async () => { try { await sendJson(`/api/bots/${encodeURIComponent(id)}/abort`, {}); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); } };
  const saveSoul = async () => { setSaving(true); try { const r = await sendJson<{ bot: BotDto }>(`/api/bots/${encodeURIComponent(id)}`, { soul }, "PATCH"); setBot(r.bot); } catch (e) { setError(e instanceof Error ? e.message : "Request failed"); } finally { setSaving(false); } };
  const rendered = useMemo(() => messages.map((m) => <div key={m.id} className={`max-w-[85%] rounded-xl px-3 py-2 text-sm ${m.role === "user" ? "ml-auto bg-accent/10" : "bg-surface"}`}><div className="whitespace-pre-wrap">{textOf(m)}</div></div>), [messages]);
  if (!bot) return <div className="p-5 text-sm text-muted">{error ?? "Loading"}</div>;
  return <div className="flex h-full min-h-0 flex-col"><div className="flex items-center gap-3 border-b border-border px-4 py-3"><Link href="/bots" className="text-sm text-muted hover:text-text">Back to bots</Link><h1 className="min-w-0 flex-1 truncate font-semibold">{bot.name}</h1><Button size="sm" variant="ghost" onClick={() => void (bot.enabled ? abort() : load())}>Stop</Button></div><div className="min-h-0 flex-1 overflow-y-auto p-4"><div className="mx-auto max-w-3xl space-y-3">{rendered}{permission && <div className="rounded-xl border border-warning/40 bg-warning-bg p-3 text-xs"><p className="font-medium">Permission required</p><p className="mt-1 break-all text-muted">{permission.message}</p><div className="mt-2 flex gap-2"><Button size="sm" onClick={() => void respond(true)}>Allow</Button><Button size="sm" variant="ghost" onClick={() => void respond(false)}>Deny</Button></div></div>}{sending && <div className="text-xs text-muted">Responding…</div>}</div></div><div className="border-t border-border p-3"><div className="mx-auto flex max-w-3xl gap-2"><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} placeholder="Message the bot" rows={2} className="min-h-12 min-w-0 flex-1 resize-none rounded-lg border border-border bg-surface px-3 py-2 text-sm outline-none focus:border-accent" />{sending ? <Button onClick={() => void abort()} variant="danger">Stop</Button> : <Button onClick={() => void send()} disabled={!prompt.trim()}>Send</Button>}</div>{error && <p role="alert" className="mx-auto mt-2 max-w-3xl text-xs text-danger">{error}</p>}</div><details className="border-t border-border px-4 py-3"><summary className="cursor-pointer text-sm font-medium">SOUL.md</summary><div className="mx-auto mt-3 max-w-3xl space-y-2"><textarea value={soul} onChange={(e) => setSoul(e.target.value)} rows={8} className="w-full rounded-lg border border-border bg-surface px-3 py-2 font-mono text-xs outline-none focus:border-accent" /><div className="flex justify-end"><Button size="sm" onClick={() => void saveSoul()} busy={saving}>Save</Button></div></div></details></div>;
}
