"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { getJson, sendJson } from "@/lib/client";
import type { BotDto, RoomDto } from "@/lib/types";
import { Button } from "@/components/ui";

export function RoomView({ id }: { id: string }) {
  const [room, setRoom] = useState<RoomDto | null>(null); const [bots, setBots] = useState<BotDto[]>([]); const [prompt, setPrompt] = useState(""); const [broadcast, setBroadcast] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => Promise.all([getJson<{ room: RoomDto }>(`/api/bots/rooms/${encodeURIComponent(id)}`), getJson<{ bots: BotDto[] }>("/api/bots")]).then(([roomResult, botResult]) => { setRoom(roomResult.room); setBots(botResult.bots); }).catch((e) => setError(e instanceof Error ? e.message : "読み込みに失敗しました")), [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const source = new EventSource(`/api/bots/rooms/${encodeURIComponent(id)}/events?epoch=${Date.now()}`); source.addEventListener("snapshot", (event) => { try { const payload = JSON.parse((event as MessageEvent).data) as { room?: RoomDto }; if (payload.room) setRoom(payload.room); } catch { setError("イベントの解析に失敗しました"); } }); source.onerror = () => source.close(); return () => source.close(); }, [id]);
  async function saveMembers(next: string[]) { if (!room) return; try { const result = await sendJson<{ room: RoomDto }>(`/api/bots/rooms/${encodeURIComponent(id)}`, { members: next }, "PATCH"); setRoom(result.room); } catch (e) { setError(e instanceof Error ? e.message : "メンバーの保存に失敗しました"); } }
  async function send() { const value = prompt.trim(); if (!value || busy) return; setPrompt(""); setError(null); setBusy(true); try { const result = await sendJson<{ room: RoomDto }>(`/api/bots/rooms/${encodeURIComponent(id)}/prompt`, { prompt: value, broadcast }); if (result.room) setRoom(result.room); } catch (e) { setError(e instanceof Error ? e.message : "リクエストに失敗しました"); } finally { setBusy(false); } }
  if (!room) return <div className="p-5 text-sm text-muted">{error ?? "読み込み中…"}</div>;
  return <div className="flex h-full min-h-0 flex-col"><div className="flex items-center gap-3 border-b border-border px-4 py-3"><Link href="/bots" className="text-sm text-muted hover:text-text">ボット</Link><h1 className="min-w-0 flex-1 truncate font-semibold">{room.name}</h1><span className="text-xs text-muted">{room.members.length} 人</span></div><div className="min-h-0 flex-1 overflow-y-auto p-4"><div className="mx-auto max-w-3xl space-y-3">{room.messages.length === 0 && <p className="text-sm text-muted">メンションされたボット だけが応答します。@everyone または「部屋に聞く」で全員に送信できます。</p>}{room.messages.map((message) => <div key={message.id} className={`max-w-[85%] rounded-xl px-3 py-2 text-sm ${message.role === "user" ? "ml-auto bg-accent/10" : "bg-surface"}`}><div className="mb-1 text-[11px] text-muted">{message.role === "user" ? "あなた" : message.botName ?? "ボット"}</div><div className="whitespace-pre-wrap">{message.text || (message.status === "working" ? "応答中…" : "")}</div></div>)}</div></div><div className="border-t border-border p-3"><div className="mx-auto max-w-3xl space-y-2"><div className="flex flex-wrap items-center gap-2 text-xs text-muted"><span>メンバー:</span>{bots.map((bot) => <label key={bot.id} className="inline-flex items-center gap-1"><input type="checkbox" checked={room.members.includes(bot.id)} onChange={(event) => void saveMembers(event.target.checked ? [...room.members, bot.id] : room.members.filter((item) => item !== bot.id))} />{bot.name}</label>)}</div><div className="flex gap-2"><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} placeholder="@ボット名 にメッセージ" rows={2} className="min-h-12 min-w-0 flex-1 resize-none rounded-lg border border-border bg-surface px-3 py-2 text-sm outline-none focus:border-accent" /><div className="flex flex-col gap-1"><Button onClick={() => void send()} disabled={!prompt.trim() || busy}>送信</Button><Button size="sm" variant={broadcast ? "primary" : "ghost"} onClick={() => setBroadcast((value) => !value)} aria-pressed={broadcast}>部屋に聞く</Button></div></div>{error && <p role="alert" className="text-xs text-danger">{error}</p>}</div></div></div>;
}
