import { NextRequest } from "next/server";
import { mkdtempSync, readdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
let root: string; const fetcher = vi.fn();
beforeEach(() => { root = mkdtempSync(join(tmpdir(), "leafcode-mcp-ingress-")); for (const [key,value] of Object.entries({LEAFCODE_PI_DATA_DIR:root,PI_CODING_AGENT_DIR:root,LEAFCODE_PI_PROCESS_ROLE:"next",NODE_ENV:"development",LEAFCODE_PI_WEBUI_AUTH:"",LEAFCODE_PI_WEBUI_TOKEN:"",LEAFCODE_PI_BACKEND_TOKEN:"owner-private-token-1234567890123456789",LEAFCODE_PI_BACKEND_GENERATION:"",LEAFCODE_PI_BACKEND_GENERATION_FILE:""})) vi.stubEnv(key,value);fetcher.mockReset(); vi.stubGlobal("fetch",fetcher); });
afterEach(() => { expect(readdirSync(root)).toEqual([]);vi.unstubAllGlobals();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true}); });
const receipt = (init: RequestInit) => ({id:new Headers(init.headers).get("x-leafcode-business-operation"),execution:"complete"});

import { GET, POST } from "./route";
it("development GET uses Backend static metadata only, not the Next config or runtime",async()=>{fetcher.mockResolvedValueOnce(Response.json({status:200,body:{servers:[],configPath:"PRIVATE",bundledConfigPath:"PRIVATE"},headers:{"set-cookie":"PRIVATE"}}));const response=await GET(new NextRequest("http://localhost/api/mcp"));expect(response.status).toBe(200);expect(await response.json()).toEqual({servers:[],configPath:"",bundledConfigPath:null});expect(response.headers.get("set-cookie")).toBeNull();expect(String(fetcher.mock.calls[0][0])).toContain("/json-business/mcp");});
it("preset POST is opaque, owner-ACKed and projects reload failures without exposing credentials",async()=>{fetcher.mockImplementationOnce(async(_url,init)=>Response.json({status:200,body:{ok:true,name:"slack",servers:[],reload:{reloaded:0,deferred:0,failed:1,errors:["PRIVATE"]},token:"PRIVATE",operation:receipt(init)}}));const body='{"preset":"slack","token":"private-fixture","command":"opaque-for-owner-to-refuse"}';const response=await POST(new NextRequest("http://localhost/api/mcp",{method:"POST",body}));expect(response.status).toBe(200);expect(JSON.stringify(await response.json())).not.toContain("PRIVATE");expect(new TextDecoder().decode(fetcher.mock.calls[0][1].body)).toBe(body);});
it.each([undefined,{id:"11111111-0123-4321-abcd-eeeeeeeeeeee",execution:"complete"}])("missing/mismatched ACK does not trigger fallback or replay",async(operation)=>{fetcher.mockResolvedValueOnce(Response.json({status:200,body:{ok:true,name:"notion",servers:[],reload:{reloaded:0,deferred:0,failed:0,errors:[]},operation}}));expect((await POST(new NextRequest("http://localhost",{method:"POST",body:"{}"}))).status).toBe(503);expect(fetcher).toHaveBeenCalledOnce();});
it("refuses Origin and oversized input before forwarding; detached owner has no fallback",async()=>{expect((await POST(new NextRequest("http://localhost",{method:"POST",headers:{origin:"https://evil.invalid"},body:"{}"}))).status).toBe(403);expect((await POST(new NextRequest("http://localhost",{method:"POST",body:"x".repeat(65537)}))).status).toBe(413);expect(fetcher).not.toHaveBeenCalled();vi.stubEnv("LEAFCODE_PI_BACKEND_TOKEN","");expect((await GET(new NextRequest("http://localhost"))).status).toBe(503);expect(fetcher).not.toHaveBeenCalled();});
