import { mkdtempSync, readdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
let root: string; const fetcher = vi.fn();
beforeEach(() => { root = mkdtempSync(join(tmpdir(), "leafcode-mcp-ingress-")); for (const [key,value] of Object.entries({LEAFCODE_PI_DATA_DIR:root,PI_CODING_AGENT_DIR:root,LEAFCODE_PI_PROCESS_ROLE:"next",NODE_ENV:"development",LEAFCODE_PI_WEBUI_AUTH:"",LEAFCODE_PI_WEBUI_TOKEN:"",LEAFCODE_PI_BACKEND_TOKEN:"owner-private-token-1234567890123456789",LEAFCODE_PI_BACKEND_GENERATION:"",LEAFCODE_PI_BACKEND_GENERATION_FILE:""})) vi.stubEnv(key,value);fetcher.mockReset(); vi.stubGlobal("fetch",fetcher); });
afterEach(() => { expect(readdirSync(root)).toEqual([]);vi.unstubAllGlobals();vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true}); });
const receipt = (init: RequestInit) => ({id:new Headers(init.headers).get("x-leafcode-business-operation"),execution:"complete"});

import { GET, POST, DELETE } from "./route";
const context = {params:Promise.resolve({name:"remote"})},auth={name:"remote",authType:"bearer",credentialConfigured:true,credentialSource:"config",credentialStatus:"present",url:"https://user:PRIVATE@example.invalid?token=PRIVATE",token:"PRIVATE"},reload={reloaded:1,deferred:0,failed:0,errors:[]};
it("GET is Backend-only and public metadata never contains stored token, URL credentials or file paths",async()=>{fetcher.mockResolvedValueOnce(Response.json({status:200,body:{...auth,configPath:"PRIVATE"}}));const response=await GET(new Request("http://localhost"),context);expect(response.status).toBe(200);expect(JSON.stringify(await response.json())).not.toContain("PRIVATE");});
it.each(['{"token":"private-token"}','{"type":"headers","headers":{"x-key":"private-value"}}','{"type":"oauth"}','{"type":"oauth","action":"complete","input":"private-code"}'])("POST relays private auth bytes without local branch: %s",async(body)=>{fetcher.mockImplementationOnce(async(_url,init)=>Response.json({status:200,body:{ok:true,auth,reload,operation:receipt(init)}}));const response=await POST(new Request("http://localhost",{method:"POST",body}),context);expect(response.status).toBe(200);expect(JSON.stringify(await response.json())).not.toContain("PRIVATE");expect(new TextDecoder().decode(fetcher.mock.calls[0][1].body)).toBe(body);});
it("DELETE forwards exact unsupported input for owner refusal, never falls back to a default destructive type",async()=>{fetcher.mockImplementationOnce(async(_url,init)=>Response.json({status:400,body:{error:"invalid",operation:receipt(init)}}));const body='{"type":"unsupported","path":"opaque"}';expect((await DELETE(new Request("http://localhost",{method:"DELETE",body}),context)).status).toBe(400);expect(new TextDecoder().decode(fetcher.mock.calls[0][1].body)).toBe(body);});
it("OAuth public state/PKCE survive but verifier-bearing URL is invalid; no silent retried flow",async()=>{fetcher.mockImplementationOnce(async(_url,init)=>Response.json({status:200,body:{ok:true,name:"remote",status:"pending",authorizationUrl:"https://auth.invalid?state=opaque&code_challenge=pkce",operation:receipt(init)}}));const response=await POST(new Request("http://localhost",{method:"POST",body:"{}"}),context);expect(response.status).toBe(200);expect((await response.json()).authorizationUrl).toContain("state=opaque");fetcher.mockImplementationOnce(async(_url,init)=>Response.json({status:200,body:{ok:true,name:"remote",status:"pending",authorizationUrl:"https://auth.invalid?code_verifier=PRIVATE",operation:receipt(init)}}));expect((await POST(new Request("http://localhost",{method:"POST",body:"{}"}),context)).status).toBe(503);expect(fetcher).toHaveBeenCalledTimes(2);});
it("credential POST requires ACK; DELETE has small bounds and POST preserves its own 2MiB bound",async()=>{fetcher.mockResolvedValueOnce(Response.json({status:200,body:{ok:true,auth,reload}}));expect((await POST(new Request("http://localhost",{method:"POST",body:"{}"}),context)).status).toBe(503);const before=fetcher.mock.calls.length;expect((await DELETE(new Request("http://localhost",{method:"DELETE",body:"x".repeat(4097)}),context)).status).toBe(413);expect((await POST(new Request("http://localhost",{method:"POST",body:"x".repeat(2*1024*1024+1)}),context)).status).toBe(413);expect(fetcher).toHaveBeenCalledTimes(before);});
