import assert from "node:assert/strict";
import test from "node:test";
import { BOT_CODE_ROUTES,botCodeTarget,botCodeBodyLimit,publicBotCodeBody } from "./bot-code-contract.mjs";
import { jsonBusinessCommand,publicJsonBusinessResult } from "./json-business-contract.mjs";
const bot="11111111-0123-4321-abcd-eeeeeeeeeeee",task={id:"code",status:"idle",token:"PRIVATE"},loop={id:"g",sessionId:"s",status:"blocked",goal:"authored 日本語",progress:[{time:"1",status:"progress",summary:"authored",token:"PRIVATE"}],token:"PRIVATE"};
test("Bot Code covers two routes/five operations; decode once and retain escaped prompt budget",()=>{assert.equal(Object.values(BOT_CODE_ROUTES).flat().length,5);for(const action of ["code-session","code-requests"]){const path="bots/"+bot+"/"+action;assert.equal(botCodeTarget(path).route,"bots/[id]/"+action);assert.equal(botCodeBodyLimit(path),action==="code-session"?262144:4096);assert.equal(jsonBusinessCommand(path,"POST"),true);assert.equal(jsonBusinessCommand(path,"GET"),false);}assert.equal(botCodeTarget("bots/%252F/code-session").params.id,"%2F");for(const path of ["bots/rooms/x/code","bots/x/code","bots/%XX/code-session"])assert.equal(botCodeTarget(path),null);assert.ok(JSON.stringify({prompt:"\u0000".repeat(32000),projectId:null}).length<botCodeBodyLimit("bots/x/code-session"));});
test("panel deep-projects only selected tasks and their Goal maps; invalid success cannot masquerade as empty",()=>{const out=publicBotCodeBody("bots/[id]/code-session",{tasks:[task],loops:{code:loop,foreign:{token:"PRIVATE"}}},200,"GET");assert.equal(out.loops.code.goal,loop.goal);assert.equal(out.loops.foreign,undefined);assert.ok(!JSON.stringify(out).includes("PRIVATE"));for(const value of [{},{tasks:[{}],loops:{}},{tasks:[],loops:[]},{tasks:[task],loops:{code:{}}}])assert.equal(publicBotCodeBody("bots/[id]/code-session",value,200,"GET"),null);assert.deepEqual(publicBotCodeBody("bots/[id]/code-session",{task:null},200,"PATCH"),{task:null});assert.equal(publicBotCodeBody("bots/[id]/code-session",{task:null},200,"POST"),null);});
test("request report/result preserve authored evidence/output and legacy strings, remove nested private data",()=>{const request={id:"a".repeat(64),codeTaskId:"code",state:"delivered",prompt:"authored 日本語",queuedAt:1,result:JSON.stringify({outcome:"done",output:"authored tool stdout",goalLoop:{status:"completed",evidence:"authored",token:"PRIVATE"},token:"PRIVATE"}),goalLoop:{status:"completed",acceptance:["authored"],token:"PRIVATE"},todoProgress:{completed:1,total:2,token:"PRIVATE"},goalLoopSummary:{status:"completed",maxTurns:3,turnCount:2,token:"PRIVATE"},token:"PRIVATE"};const out=publicBotCodeBody("bots/[id]/code-requests",{requests:[request]},200,"GET");assert.ok(!JSON.stringify(out).includes("PRIVATE"));assert.equal(JSON.parse(out.requests[0].result).output,"authored tool stdout");assert.equal(out.requests[0].goalLoop.acceptance[0],"authored");assert.equal(publicBotCodeBody("bots/[id]/code-requests",{requests:[{...request,result:"legacy authored text"}]},200,"GET").requests[0].result,"legacy authored text");assert.equal(publicBotCodeBody("bots/[id]/code-requests",{requests:[{...request,state:"bogus"}]},200,"GET"),null);});
test("commands preserve nullable clears, observed Goal state and receipts, strip owner headers",()=>{for(const [method,value]of [["POST",{task}],["PATCH",{loop}],["PATCH",{loop:null}],["PATCH",{task:null}]])assert.ok(publicBotCodeBody("bots/[id]/code-session",value,200,method));assert.deepEqual(publicBotCodeBody("bots/[id]/code-requests",{requestId:"a",state:"ready",task,operation:{id:bot,execution:"complete",token:"PRIVATE"}},200,"POST"),{requestId:"a",state:"ready",task:{id:"code",status:"idle"},operation:{id:bot,execution:"complete"}});assert.equal(publicJsonBusinessResult("bots/"+bot+"/code-session",{status:200,body:{task},headers:{"set-cookie":"PRIVATE"}},"POST").headers["set-cookie"],undefined);});
